### ISSUE TITLE
Could this be ported to VSCODE editor as an extension?

### ISSUE THREAD

**Issue by apoorvpandey0** [foss42/apidash#10]
I just want to ask if this is possible for Flutter apps?

**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I would love to use this if this was integrated into VSCODE as an extension

**Comment by ashitaprasad** [comment]
Nice suggestion, but currently it is not possible for Flutter apps. 
Will definitely keep this feature in mind for a future release.
