### ISSUE TITLE
Add more HTTP headers suggestions

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#105]
The current list of HTTP headers ([Link](https://github.com/foss42/apidash/blob/main/lib/utils/header_utils.dart)) is not exhaustive.
We need to add more headers to the existing list. Make sure these headers are only those headers that are sent by client in the request and not response headers. It is used for auto-suggesting headers to the user.

Note: This issue will remain open perpetually so that people can know about it and add missing headers from time to time.

**Comment by tanishgl** [comment]
Hi @ashitaprasad . 

I can take up this issue. 
1. I've curated a list of a few HTTP headers suggestions. (I can share the KV-pairs here if you'd like)
2. I've created relevant tests for the same.

**Comment by ashitaprasad** [comment]
Sure @tanishgl, you can send across a PR.

**Comment by opxdelwin** [comment]
Hey @ashitaprasad, is this issue still unresolved? Are we looking for more headers?

**Comment by ashitaprasad** [comment]
@opxdelwin this issue will remain open perpetually so that people can know about it and add missing headers from time to time.

**Comment by Yousef-Rabia** [comment]
@ashitaprasad @animator 

Do you consider [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) as a reputed site for a source?

**Comment by animator** [comment]
@Yousef-Rabia Yes it is a reputed source.
