### ISSUE TITLE
Renderflex overflow error for longer response key names

### ISSUE THREAD

**Issue by tanishgl** [foss42/apidash#106]
**Bug Description**
Renderflex overflows horizontally in a situation where the API response of content-type : application/json have a key-value pair whose key name is too long to fit in the Json-previewer widget.

**Steps to Reproduce the bug/problem**
1. Make a GET request to this endpoint [api.foss42.com/country/codes](url)
2. After getting the response, scroll down in the preview mode to come across a lenthy-named key. (For reference, a screenshot has been attached).
<img width="960" alt="Screenshot 2024-01-01 153807" src="https://github.com/foss42/apidash/assets/73936719/d5607181-b29d-4d82-90a1-564c4fbd6bfb">

**Expected behavior**
Following solutions are viable :- 
1. We can slice lengthy key names to a fixed length of characters followed by ellipsis (to indicate that the key is indeed shortened). 
2. Instead of using an EqualSplitView to display the request pane and response pane half and half, the response pane can be provided some extra weight in such specific case.

**Device Info (The device where you encountered this issue):**
 - OS: Windows
 - Version: Windows 11 22H2

**Comment by ashitaprasad** [comment]
Thank you for pointing out this bug @tanishgl and some potential solutions.
We will definitely work on resolving it.

**Comment by ashitaprasad** [comment]
The issue requires modification in the json_data_explorer [fork](https://github.com/foss42/json_data_explorer) that we are currently maintaining for API Dash.
