### ISSUE TITLE
Make Cancel-able HTTP Requests

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#109]
Currently, when you press the Send Button, a request is sent and the UI waits for it to complete.
In case no response is sent for a very long time (server might hang), there should be a provision to cancel the request instead of restarting the entire app.

**Comment by yashas-hm** [comment]
Hi, may I work on this?

**Comment by ashitaprasad** [comment]
Sure @yashas-hm 
Please go ahead and send across a PR for this feature.

**Comment by yashas-hm** [comment]
@ashitaprasad  Solved Issue in PR #113

**Comment by yashas-hm** [comment]
As @animator said that api dash is not planning to migrate to Dio, [Unwired](https://pub.dev/packages/unwired) package can be used for cancelling requests. It is built on top of http requests.

If this is go ahead from the maintainers I can work on it.

**Comment by sasanktumpati** [comment]
@animator @ashitaprasad  I've implemented request cancellation functionality in this PR #507  . Let me know if you'd like any changes or have questions.
