### ISSUE TITLE
Users should be able to fire multiple requests in parallel

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#114]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently only one request can be sent via API Dash. Once a request is sent, it shows `Busy` when the user navigates to any other request. If a request takes too long to execute, this leads to a bottleneck as users cannot do any other task. Users should be allowed to send  multiple requests in parallel with proper state management.

**Comment by sam-shot** [comment]
I'd like to work on this

**Comment by nikkivirtuoso** [comment]
Hello everyone, I have tried something that I want to share, is it suitable to first collect all the apis and then send requests , I have created something like as below:
<img width="1470" alt="Screenshot 2024-02-25 at 9 51 37 PM" src="https://github.com/foss42/apidash/assets/148634283/937d777f-65ae-445b-a436-83e3a7e49f0b">

**Comment by animator** [comment]
@nikkivirtuoso is there a link to the project where I can review your approach?

**Comment by nikkivirtuoso** [comment]
@animator here is my approach sir, 
I have simply first inserted all the API's request in a list and then iterate over them to get the response of all the APIs this is how i tried to make multiple APIs execution

**Comment by nikkivirtuoso** [comment]
if an API call failed to response then it will simply display no response in the response section

**Comment by ashitaprasad** [comment]
@nikkivirtuoso to get feedback you need to provide project link where you have implemented your approach as mentioned by @animator

**Comment by nikkivirtuoso** [comment]
import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Multiple API Requests Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> responses = [];
  List<String> urls = [];

  TextEditingController _urlController = TextEditingController();

  Future<void> fetchAPIs(List<String> urls) async {
    List<Future<http.Response>> futures = [];
    for (String url in urls) {
      futures.add(http.get(Uri.parse(url)));
    }
    List<http.Response> results = await Future.wait(futures);
    for (http.Response response in results) {
      if (response.statusCode == 200) {
        setState(() {
          responses.add(response.body);
        });
      } else {
        throw Exception('Failed to load data');
      }
    }
  }

  Future<void> fetchData() async {
    await fetchAPIs(urls);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Multiple API Requests Example'),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _urlController,
                    decoration: InputDecoration(labelText: 'Enter API URL'),
                  ),
                ),
                IconButton(
                  icon: Icon(Icons.add),
                  onPressed: () {
                    setState(() {
                      urls.add(_urlController.text);
                      _urlController.clear();
                    });
                  },
                ),
              ],
            ),
          ),
          Expanded(
            child: ListView.builder(
              itemCount: responses.length,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text('Response ${index + 1}'),
                  subtitle: Text(responses[index]),
                );
              },
            ),
          ),
          ElevatedButton(
            onPressed: fetchData,
            child: Text('Fetch Data'),
          ),
        ],
      ),
    );
  }
}
here is the code

**Comment by nikkivirtuoso** [comment]
https://github.com/nikkivirtuoso/concurrent_api_calls
here is the link of the file

**Comment by animator** [comment]
@nikkivirtuoso The approach is not correct as you are waiting for all requests to complete and then processing the List of responses.
Also, going forward please send across a PR where your solution is integrated in API Dash instead of standalone snippets and screenshots.

**Comment by jashwanth0712** [comment]
To fire multiple requests in parallel , i believe we might need to create some sort of named collection of requests as discussed in #24 , as of now we only have list of requests , can i work on creating the named collections like the following image
![image](https://github.com/foss42/apidash/assets/74978383/93394591-734d-4611-9408-0c9f77b76f6d)
