### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#119]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add few end-to-end integration tests to automate some user testing workflows.

**Comment by Drakennnnn** [comment]
Hi i would like to work on this issue. It will take a little time to integrate the test files and include related dependencies. Sometimes the debug message of the API calling can be misleading. Please let me know if theres something else to be included. Thank you.

**Comment by animator** [comment]
@Drakennnnn The issue is not about integrating the test files. We already have automated testing in place. 
Integration testing is a totally different concept. You can read more about it [here](https://docs.flutter.dev/testing/integration-tests).

**Comment by Drakennnnn** [comment]
Hey @animator, thanks for the clarification, I do have an idea of GUI testing. As API dash currently only has a desktop application, I don't think I will be needing FireBase test lab. Please let me know otherwise. I will start working on the code right away. 

Regards
Sudip

**Comment by Drakennnnn** [comment]
@animator I have gone through the article you have shared. As API DASH is a desktop application, we cannot use firebase test tool and have to write code covering every aspect of the app. Its a easy task but lot of code to type. I will be done with it within a week. I am having a little trouble with the code want to know if theres a easier way to implement the code for testing the codegens or should I leave it from the code as of now and it can be tested manually in the meanwhile. Thank You. 
![Screenshot 2024-03-05 235857](https://github.com/foss42/apidash/assets/152934286/2a9f32cc-2fa5-48e3-b228-01ca79958fd6)

**Comment by ashitaprasad** [comment]
@Drakennnnn I will suggest you to start writing some widget tests for some screens and once you are well versed you can move onto integration testing.

**Comment by Drakennnnn** [comment]
@animator @ashitaprasad I am done with writing around 60-70% of the tests. These tests are UX based and covers the app as whole. Unfortunately I will have to pause until the 22nd as my exams will be starting. Hope that's okay. I can share what I have done until now if required. Thank you.

**Comment by animator** [comment]
@Drakennnnn you can send across a PR so that we can review the existing work.

**Comment by ashitaprasad** [comment]
Integration tests have been added by @DenserMeerkat
