### ISSUE TITLE
Importing from cURL

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#126]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Quickly import cURL files to API Dash
Drag & Drop import is preferred.

**Comment by ketan-sonar** [comment]
Should I put a button saying "+ Import" besides the button saying "+ New" to import a request? Upon clicking this button, the user will be able to upload different types of files such as, RAML, WADL, WSDL, cURL, etc. The user will also be able to upload the file by dragging and dropping it here.

<img width="1302" alt="Screenshot 2024-06-30 at 22 06 37" src="https://github.com/foss42/apidash/assets/62693272/216a8d43-26c0-47be-8109-71f41b622dd3">

**Comment by ashitaprasad** [comment]
@ketan-sonar
Apart from adding the +Import button, the entire functionality has to be built i.e., selecting the cURL file, parsing it and creating the requests model, populating the collection provider etc.

**Comment by ketan-sonar** [comment]
Can I use an external library like [flutter_dropzone](https://pub.dev/packages/flutter_dropzone) to accomplish this task?

**Comment by ketan-sonar** [comment]
We will have to use Platform Channels, which allow us to implement native functionality (like file drag-and-drop) and integrate it with our Flutter application.

**Comment by ashitaprasad** [comment]
Sure @ketan-sonar, you can send across a draft PR. Will review it.
