### ISSUE TITLE
Importing from RAML file

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#129]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Learn more about [RAML](https://en.wikipedia.org/wiki/RAML_(software))

Add support for importing requests from RAML file.

**Comment by AnanyaSinghal23** [comment]
Can you please give an idea about how these importing files work. I would like to work on the issues once I am able to understand the concept.

**Comment by animator** [comment]
@AnanyaSinghal23 You need to develop this feature end to end. Currently, there is no provision to import a file in API Dash.
You can send across a preliminary PR to discuss your approach.

**Comment by AnanyaSinghal23** [comment]
Okay

**Comment by Clasherzz** [comment]
this is intresting. First time hearing about RAML . I would love to work on this. But would love to know how should the parsing of RAML must work. Like quick searches shown me there are java raml parser and other similar stuffs . But nothing of that sort is there for dart. So should i manually parse through the RAML File checking for each endpoint and then for the body and responses . There after use request model class to generate objects. Or is there some other way ? Is this what is aimed by saying importing of RAML File

**Comment by ashitaprasad** [comment]
@Clasherzz A good point to start will be to take a look at curl importer [here](https://github.com/foss42/apidash/tree/main/lib/importer)
We have our own fork of parser we use for cURL available here - https://github.com/foss42/curl_converter
For RAML, it should be something similar .. you will need to create a pure dart RAML parser first which will reside [here](https://github.com/foss42/apidash/tree/main/packages). It will take the contents of RAML file (string) as an input and parse it and return the contents which can be used to create the API Dash request models. It will have its own tests.
This parser will be added to apidash's pubspec and the relevant raml improter will be added [here](https://github.com/foss42/apidash/tree/main/lib/importer)

**Comment by Clasherzz** [comment]
I see. So the ui change would also be a simple addition of raml in the import button right

**Comment by ashitaprasad** [comment]
Yes. The frontend is already implemented.
The only change required will be the addition on RAML in ImportFormat enum and adding the parser code.
https://github.com/foss42/apidash/blob/b6cdf60365d6c8e1fcd6487b22e6bd77f373ac7a/lib/consts.dart#L145-L150

**Comment by Clasherzz** [comment]
okayy

**Comment by ashitaprasad** [comment]
Yes

**Comment by Clasherzz** [comment]
> It does not matter .. The user is anyways selecting the import format.
> Whether he provides a txt, yml, yaml, raml, etc .. it does not matter as long as there is no parsing error.

Ohh yeah i see it now
