### ISSUE TITLE
Add CodeGen for Go (http)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#130]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add code generator for Go 
Library - https://pkg.go.dev/net/http

**Comment by CodeHariK** [comment]
Can you elaborate

**Comment by animator** [comment]
@CodeHariK To get a fair idea of the API Dash codegen, check out the codes in the `lib/codegen` folder for languages that have been already implemented like python, kotlin etc. Usually implementing a codegen for a new language/library in API Dash requires:

1. Some idea of how jinja template works
2. Some idea of library/language specific client code that you are generating as the generated code should be as natural (not spaghetti) as possible for someone who is already familiar with the language/library.
3. You need to also verify the generated code and write appropriate test cases to cover the various model input scenarios.

Related Link - https://github.com/foss42/apidash/discussions/80

**Comment by animator** [comment]
@CodeHariK yes

**Comment by animator** [comment]
Sure you can refer to the existing codegens and send across a PR for review when ready.

**Comment by apoorvdwi** [comment]
@ashitaprasad @animator is this issue still open to work on?
