### ISSUE TITLE
Add CodeGen for C# (HttpClient)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#132]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add code generator for C#
Library - https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-8.0

**Comment by levo-777** [comment]
what do you mean exactly , do you want to add the http client library / C# into your codebase ?

**Comment by ashitaprasad** [comment]
@levo-777, if you get a chance check out the codegen for languages already implemented like python, kotlin etc. to get a better idea. Usually implementing a codegen for API Dash requires

1. A fair idea of how jinja template works
2. A fair idea of library/language specific client code that you are generating as the generated code should be as natural as possible for someone who is already familiar to the language/library
3. You need to also verify the generated code and write appropriate test cases to cover the various model input scenarios

Related Link - https://github.com/foss42/apidash/discussions/80

**Comment by animator** [comment]
@levo-777 That is what point 2 mentioned above by @ashitaprasad refers to. You have to think about the logic, work on the implementation and generate the code such that it is as natural as someone would have written if he/she was already familiar with the language/library.

**Comment by mohnishdeshpande** [comment]
On it!

**Comment by mohnishdeshpande** [comment]
@ashitaprasad I have finished the codegen and written tests as well. All tests pass and functionality has been cross checked. Please have a look and let me know.
