### ISSUE TITLE
Verify CodeGen & add test cases for Java (async-http-client)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#136]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Java
Library - [async-http-client](https://github.com/AsyncHttpClient/async-http-client)

More info here - #80

**Comment by Drakennnnn** [comment]
Dear Ma'am,

After looking at the issue and going through other similar issues and your responses, I would like to carry on these steps.

- Creating Jinja templates specifically designed for generating Java code that utilizes the async -http-client library.
- Determining the structure of Java code, including function calls, parameter passing, and error handling, based on common patterns seen in Java code.
- Inserting placeholders within the Jinja templates to dynamically insert API endpoint URLs, headers, query parameters, request bodies, and other relevant information.
- Defining placeholders for variables that will be replaced with actual values when generating code based on user input or API specifications.
- Integrating the Java code generation feature into API Dash's existing codebase, ensuring compatibility with the Jinja templating engine and existing code generation workflows.
- Implementing logic to parse user input like API endpoint URLs, headers, parameters and populate the Jinja templates accordingly to generate Java code dynamically.
- Writing comprehensive test cases to cover various input scenarios, including different HTTP methods (GET, POST, PUT, DELETE), headers, query parameters, and request bodies.
- Performing integration tests to ensure that the code generation feature behaves as intended within the API Dash application.
- Providing clear instructions on how to use it and examples of generated Java code snippets.
- Gathering feedback from users and community to gather insights on the usability and effectiveness of the Java code generation feature and continuously monitoring the functionality.

These are the detailed steps. Please let me know if something needs to be changed. I would also like to know if the previous contributions used jinja or jinja2.

Thank you.
Sudip Maroj (Draken)
