### ISSUE TITLE
Validate Java (HTTP Client) CodeGen & add all test cases

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#137]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Java
Library - https://openjdk.org/groups/net/httpclient/intro.html

More info here - #80

**Comment by Mj9909** [comment]
I want to work on this issue

**Comment by animator** [comment]
@Mj9909 You are free to work on it and send across a PR.

**Comment by sibghatullah78** [comment]
Did this issue is added already if you can update me I want to work over this

**Comment by sibghatullah78** [comment]
Okay sir
