### ISSUE TITLE
Add CodeGen for C (Libcurl)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#138]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for C
Library - libcurl

**Comment by MohamedAliBadawy** [comment]
Can I work on this issue?

**Comment by mohnishdeshpande** [comment]
@ashitaprasad On it!

**Comment by nikkivirtuoso** [comment]
@ashitaprasad ma'am , please have a look I have prepared a solution for creating the code generation for C using the library - libcurl
 https://github.com/nikkivirtuoso/ConvertToC/blob/main/lib/main.dart

**Comment by nikkivirtuoso** [comment]
@ashitaprasad ma'am, i have updated the code, Now we can generate code of 
                'C',
                'Ruby (Faraday)',
                'Rust (curl-rust)',
                'Rust (reqwest)',
                'Rust (Hyper)',
                'Ruby (Net::Http)',
                'R (Crul)',
                'R (Httr)',

**Comment by nikkivirtuoso** [comment]
please have a look

**Comment by nikkivirtuoso** [comment]
<img width="1470" alt="Screenshot 2024-02-28 at 7 36 47 PM" src="https://github.com/foss42/apidash/assets/148634283/07818548-cae4-4817-8c5e-37e46f89f87e">
<img width="1470" alt="Screenshot 2024-02-28 at 7 36 50 PM" src="https://github.com/foss42/apidash/assets/148634283/47a979f2-1f92-4660-9fde-25e8c194fe4e">

**Comment by mohnishdeshpande** [comment]
@animator I have update the PR with test cases. It should now be all set to go.

**Comment by mohnishdeshpande** [comment]
@animator Please have a look at the PR. I have made changes as suggested before.
