### ISSUE TITLE
Add CodeGen for Swift (URLSession)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#140]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Swift 
Library - [URLSession](https://developer.apple.com/documentation/foundation/urlsession)

Guidelines for adding a codegen - https://github.com/foss42/apidash/discussions/80

**Comment by deepraj02** [comment]
is anyone currently working on it, I would like to take it :)

**Comment by ashitaprasad** [comment]
@deepraj02 Sure, you can go ahead and work on this issue.

**Comment by deepraj02** [comment]
Thanks, also I see one closed PR for this issue can you guide me what's wrong with that, so I would avoid that.

**Comment by ashitaprasad** [comment]
@deepraj02 Please make sure you follow these guidelines https://github.com/foss42/apidash/discussions/80 while working on this issue.

**Comment by deepraj02** [comment]
Got it, Thanks
