### ISSUE TITLE
Add CodeGen for OCaml (cohttp)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#141]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for OCaml
Library - [cohttp](https://github.com/mirage/ocaml-cohttp)

Guidelines for adding a codegen - https://github.com/foss42/apidash/discussions/80

**Comment by nilaygit-10721** [comment]
please assign me this issue

**Comment by ashitaprasad** [comment]
@nilaygit-10721 We do not assign any issues. Anyone can work on the issue and submit a PR.
