### ISSUE TITLE
Add CodeGen for PHP (HTTPlug)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#144]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for PHP
Library - https://github.com/php-http/httplug

**Comment by nikkivirtuoso** [comment]
@ashitaprasad ma'am in the mentioned link it is using the abondaned packages like ```php-http/guzzle6-adapter``` i think this is not the correct way of taking the API request

**Comment by animator** [comment]
@nikkivirtuoso Check out this link - https://docs.php-http.org/en/latest/httplug/tutorial.html for tutorials and see if there is still any issue while running the code.
