### ISSUE TITLE
Add CodeGen for R (httr)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#145]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for R
Library - https://github.com/r-lib/httr

Follow the instructions provided [here](https://github.com/foss42/apidash/discussions/80)

**Comment by ayush-mahawar26** [comment]
May I work on this issue?

**Comment by ashitaprasad** [comment]
Sure @ayush-mahawar26
