### ISSUE TITLE
Add CodeGen for R (crul)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#146]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for R
Library - https://github.com/ropensci/crul

Guidelines for adding a codegen - https://github.com/foss42/apidash/discussions/80

**Comment by Drakennnnn** [comment]
Dear Ma'am, 

After looking at the issue and going through other similar issues and your responses, I would like to carry on these steps.

- Creating Jinja templates specifically designed for generating R code that utilizes the curl library.
- Determining the structure of the R code, including function calls, parameter passing, and error handling, based on common patterns seen in R code using curl.
- Inserting placeholders within the Jinja templates to dynamically insert API endpoint URLs, headers, query parameters, request bodies, and other relevant information.
- Defining placeholders for variables that will be replaced with actual values when generating code based on user input or API specifications.
- Integrating the R code generation feature into API Dash's existing codebase, ensuring compatibility with the Jinja templating engine and existing code generation workflows.
- Implementing logic to parse user input like API endpoint URLs, headers, parameters and populate the Jinja templates accordingly to generate R code dynamically.
- Writing comprehensive test cases to cover various input scenarios, including different HTTP methods (GET, POST, PUT, DELETE), headers, query parameters, and request bodies.
- Performing integration tests to ensure that the code generation feature behaves as intended within the API Dash application.
- Providing clear instructions on how to use it and examples of generated R code snippets.
- Gathering feedback from users and community to gather insights on the usability and effectiveness of the R code generation feature and continuously monitoring the functionality.

These are the detailed steps. Please let me know if something needs to be changed. I would also like to know if the previous contributions used jinja or jinja2. 

Thank you. 
Sudip Maroj (Draken)
