### ISSUE TITLE
Add CodeGen for Rust (ureq)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#152]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Rust
Library - https://github.com/algesten/ureq

**Comment by jashwanth0712** [comment]
hi @ashitaprasad , at the initial glance what i understand is codegen for any language is just filling of the user entered url and body into the boiler plate code programatically , please correct me if there is any extra checks or conditions to be taken care of

**Comment by ashitaprasad** [comment]
@jashwanth0712, if you get a chance check out the codegen for languages already implemented like python, kotlin etc. to get a better idea. Usually implementing a codegen for API Dash requires 

1. A fair idea of how jinja template works
2. A fair idea of library/language specific client code that you are generating as the generated code should be as natural as possible for someone who is already familiar to the language/library 
3. You need to also verify the generated code and write appropriate test cases to cover the various model input scenarios
