### ISSUE TITLE
Add response previewer for text/csv

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#156]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Users should be able to see rendered table in response preview.

**Comment by tejas-raskar** [comment]
Hey @ashitaprasad! 
I would like to work on this issue

**Comment by ashitaprasad** [comment]
Sure @tejas-raskar, you can send across a PR so that we can discuss on it further.

**Comment by Mj9909** [comment]
Hey @ashitaprasad I want to work on this issue

**Comment by ashitaprasad** [comment]
Sure @Mj9909, you can work across the issue and send across a PR.
