### ISSUE TITLE
cURL initial view code error

### ISSUE THREAD

**Issue by CH1NRU5T** [foss42/apidash#157]
**Describe the bug/problem**
When we start the app for first time, the default codegen language is cURL, and if we press the `View Code` button without typing anything in the url tab, then is shows an error.

**Steps to Reproduce the bug/problem**
Initially launching the app:
![init](https://github.com/foss42/apidash/assets/72245838/057862bb-cab5-4d07-b00c-cbc8fd4f34fa)
After pressing the `View Code` button:
![initViewCodeButtonPressed](https://github.com/foss42/apidash/assets/72245838/a5117f8e-406a-423e-bd7e-5e29cd760abd)

**Expected behavior**
This should not show an error, instead it should show 
`curl --url '' `

**Device Info (The device where you encountered this issue):**
 - OS: [MacOS]
 - Version: [Sonoma 14.3.1]

**Comment by CH1NRU5T** [comment]
I have a query regarding the test cases.
```dart
test('GET 7', () {
      const expectedCode = r"""curl --url 'https://api.foss42.com'""";
      expect(curlCodeGen.getCode(requestModelGet7, "https"), expectedCode);
    });
```
```dart
/// GET request model with body
const requestModelGet7 = RequestModel(
  id: 'get7',
  url: 'https://api.foss42.com',
  method: HTTPVerb.get,
  requestBodyContentType: ContentType.text,
  requestBody:
      'This is a random text which should not be attached with a GET request',
);
```

What this test case is expecting that if I have a GET request, then anything written in the BODY should not be attached.
Quoting [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.1)
`A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.`

Which means, that a GET request can have a body, it depends on how server is handling it.
Also referencing an [article](https://www.elastic.co/guide/en/elasticsearch/guide/current/_empty_search.html) by elastic search, which uses get requests with body to return data.

Thoughts on this @animator @ashitaprasad  ?

**Comment by animator** [comment]
@CH1NRU5T 
Mozilla docs reads [Requests using GET should only be used to request data (they shouldn't include data)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET)

Also, many REST clients do not permit sending body with GET requests like dart http or python requests.

Do take a look at this [article](https://www.baeldung.com/http-get-with-body). It mentions how later version of RFC tightened the usage of content in GET.

elasticsearch is an exception (the doc you attached is very old) and not the norm. They started providing POST endpoints in later versions.

**Comment by CH1NRU5T** [comment]
@animator Sure, the docs **suggest** one should not attach the body with a GET request.
But as a REST API Client, shouldn't Api Dash allow the users to send it anyway?
The user should be aware of the fact that sending a body with a GET request is not suggested.
Postman allows us to send a body with a GET request.

**Comment by animator** [comment]
This topic has been discussed earlier where we took the design decision to stick to the best practices.
It is also coupled by the fact that many libraries being used in the language specific generated codes do not allow attaching body in GET request.

**Comment by CH1NRU5T** [comment]
Alright, Thank you for the clarification.

**Comment by CH1NRU5T** [comment]
Another query regarding a test case!
```dart
test('GET 3', () {
      const expectedCode =
          r"""curl --url 'https://api.foss42.com/country/data?code=IND'""";
      expect(curlCodeGen.getCode(requestModelGet3, "https"), expectedCode);
    });
```
```dart
/// GET request model with override query params
const requestModelGet3 = RequestModel(
  id: 'get3',
  url: 'https://api.foss42.com/country/data?code=US',
  method: HTTPVerb.get,
  requestParams: [
    NameValueModel(name: 'code', value: 'IND'),
  ],
);
```
This test case is when you already have a request param in your URL, and you additionally add a param with the same key in the params list, then the one on the list should be presented in the final output on generated code.
I think that the one written in the params tab should be appended at the end of the cURL request.
It should look like this:
```curl --url 'https://api.foss42.com/country/data?code=US&code=IND'```

**Comment by animator** [comment]
Issue is not just with cURL but also other codegens as reported in #183 #201

**Comment by PCoder23** [comment]
@animator should we add just a single global response for the all the codegens when the url is empty, it will not just only solve the problems for the current codegens, but for the upcoming unhandle codegens too ?

**Comment by CH1NRU5T** [comment]
@PCoder23 I think we have those, `kTemplateStart`.
According to me, the main issue seems to be, that for every codegen we are calling the `requestModelToHARJsonRequest()` method, and from this method's response we are proceeding to generate the code.
I think we should not use the `requestModelToHARJsonRequest()` method because we already have the `requestModel`, so we should proceed with it, without converting it to JSON and all that procedure.
@animator thoughts on this?

**Comment by ashitaprasad** [comment]
The issue has been resolved in the main branch using a fallback URL in case one is missing.
