### ISSUE TITLE
Redundant payload when formdata selected as body type

### ISSUE THREAD

**Issue by Tanish2002** [foss42/apidash#160]
**Describe the bug/problem**
As discussed on Discord, when FormData is selected as body. A payload variable is created which contains the data from the json/text body field if entered previously. This is not required when using multiform data.

**Steps to Reproduce the bug/problem**
1. Click on POST type request and add a POST endpoint.
2. Open Body in click on `text` or `json`, and type some payload.
3. Now click on `formdata` without clearing the previous field.
4. Now lastly check code generation for any of the following languages
- Python (requests)
- Python (http.client)
- Node.js (fetch)
- Node.js (axios)
- Javascript (fetch)
- Javascript (axios)
- Dart (http)
- HAR
- CURL
 

**Expected behavior**
body from the text or json field shouldn't be shown in form data field

**Comment by animator** [comment]
Thnaks for reporting the issue and sending across a PR.
