### ISSUE TITLE
Add Linux build for NixOS

### ISSUE THREAD

**Issue by Tanish2002** [foss42/apidash#162]
Currently the project on linux is only packaged for Arch Linux, RPM based distros and Debian based distros. 
We should have a Linux build for [NixOS](https://nixos.org/)

**Comment by animator** [comment]
@Tanish2002 Can you share some details on how software publishing and distributing works in nixOS ecosystem.

**Comment by Tanish2002** [comment]
The process for publishing isn't hard.

The first part is creating a working package.
1. You need to know the nix language(A functional programming language). 
2. You'll have to create a package using the nix language, and check if it builds fine on your system
3. You can then simply create a PR to the [nixpkgs repo](https://github.com/NixOS/nixpkgs)
4. Their bot can check if the package builds for all the platforms they support, you can omit certain platforms in the package.
5. If they approve of the package, they'll merge it into master branch, after a few days it will be merged with the nixos-unstable branch. In the next major release of the OS it will be included.

Note: nixpkgs does provide some [helper functions](https://nixos.org/manual/nixpkgs/stable/#ssec-dart-flutter) for creating flutter applications which should make it easy to package

I'll see if I can create a package myself.😄

**Comment by animator** [comment]
Thanks for the info @Tanish2002 
Also, is there any guide available which tells how to setup Flutter and install dev dependencies required for desktop app development in nixOS?

**Comment by Tanish2002** [comment]
@animator There is no blog/guide available.
There's the [nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/)
The section regarding flutter applications: [here](https://nixos.org/manual/nixpkgs/unstable/#ssec-dart-flutter).

I tried to build a package for NixOS, The biggest problem is the `printing` package that we use for PDF preview.
It tried to download a [pdfium](https://github.com/bblanchon/pdfium-binaries/) binary from the internet.

In NixOS packages are built in a sandbox without internet, so the build fails since it can't download the package. To make it worrk we would need to provide the pdfium binary to the  `printing` package and disable it from downloading it.

I've created an [issue](https://github.com/DavBfr/dart_pdf/issues/1615) on printing package repo to discuss a potential workaround.

**Comment by animator** [comment]
Closing this issue so that we can have a single channel of discussion on the primary discussion thread https://github.com/foss42/apidash/discussions/240
All the nixOS related discussion in this thread can be referred by people as it is already linked at the start of the discussion.
