### ISSUE TITLE
Improving UI of Settings Page

### ISSUE THREAD

**Issue by BrawlerXull** [foss42/apidash#168]
Changed the UI of settings page and and it more beautiful

**Describe the solution/feature you'd like us to add**
I've attached new UI below 
<img width="323" alt="Screenshot 2024-02-23 at 10 46 19 PM" 
src="https://github.com/foss42/apidash/assets/111864031/d9e3cfe0-cf30-4a8b-95f8-deb222da6e02">
<img width="1440" alt="Screenshot 2024-02-23 at 10 58 36 PM" src="https://github.com/foss42/apidash/assets/111864031/6abc3f41-a4c0-4b2f-8f24-300ce379f40d">

<img width="321" alt="Screenshot 2024-02-23 at 10 46 59 PM" src="https://github.com/foss42/apidash/assets/111864031/a6238e6c-97e2-42c9-8d3d-fe0dd4e1bdbd">

**Comment by animator** [comment]
The current Settings screen is as per Material Design 3 and currently we are not incorporating any new changes to it until there is any UI break.
