### ISSUE TITLE
Add video player support for viewing response of video mimetype

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#17]
**Use case**

User should be able to directly play video in the response pane when the response is of content type video/H264, video/H265, video/mp4 etc. Full list of mimetypes available [here](https://www.iana.org/assignments/media-types/media-types.xhtml#video). Currently, the app allows users to download the video response.

**Comment by Utkarsh4517** [comment]
I want to work on this can you please assign this to me @ashitaprasad

**Comment by Harsh1350** [comment]
I want to work for this issue Please assign this to me @ashitaprasad

**Comment by ashitaprasad** [comment]
Hi @Utkarsh4517 @Harsh1350,
Firstly, Join our [discord server](https://bit.ly/heyfoss) so that you can message on the **#foss** channel whenever you encounter any issue. That is also our official channel where we have all discussions related to API Dash.
You must also follow the [Contribution Guidelines](https://github.com/foss42/api-dash/blob/main/CONTRIBUTING.md).
We currently do not assign an issue to a single person, as it might not be the best approach. 
Also, before sending a PR, just let me know when your code is ready for review.

**Comment by Nirsu** [comment]
Hi !
I would like to work on this issue, I posted a message on discord :)

**Comment by animator** [comment]
Sure @Nirsu
Please feel free to work on the issue and send across a PR.
If you have any query, kindly drop a message on the discord channel.

**Comment by monstajoe2002** [comment]
I saw that there's a closed PR for this issue. Can I still work on it?

**Comment by animator** [comment]
@monstajoe2002 yes you can.

**Comment by monstajoe2002** [comment]
I created a PR here: https://github.com/foss42/apidash/pull/298
