### ISSUE TITLE
Adding a clear button to clear the requests data from the home page itself

### ISSUE THREAD

**Issue by BrawlerXull** [foss42/apidash#170]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I was thinking about adding a clear button to the home page which will increase user experience as currently manually have to navigate to setting page to clear the data

**Describe the solution/feature you'd like us to add**
```
TextButton.icon(
        onPressed: () {
          ref
              .read(collectionStateNotifierProvider.notifier)
              .clearData();
        },
        icon: const Icon(
          Icons.clear_all,
          size: 20,
        ),
        label: const Text(
          'Clear',
          style: kTextStyleButton,
        ),
      ),
```
I was thinking of adding this button in the homepage for clearing data 
i can add a confirmation message if needed

UI after proposed changes
<img width="1440" alt="Screenshot 2024-02-24 at 12 14 56 AM" src="https://github.com/foss42/apidash/assets/111864031/b4c05db9-028f-4a6c-b760-66b61b5d7068">

**Comment by animator** [comment]
We will not add this button in the collection pane as anyone can click by mistake and clear everything. 
It is a danger setting and has been provided in the settings page.
![Screenshot 2024-02-24 at 3 27 39 AM](https://github.com/foss42/apidash/assets/615622/535d7b16-9fdc-4139-89af-a8ac90243f72)

Closing this issue.
