### ISSUE TITLE
Adding a snackbar if the session data is empty after clicking on save button

### ISSUE THREAD

**Issue by BrawlerXull** [foss42/apidash#172]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently user can click on save button and save data even if it is empty I added a validation to the data to see if it's empty if its empty then show Snackbar 

https://github.com/foss42/apidash/assets/111864031/41be6415-1c16-4b22-82f9-d0828148bd5e

**Describe the solution/feature you'd like us to add**
```
TextButton.icon(
      onPressed: savingData
          ? null
          : () async {
              var itemIds = ref.read(requestSequenceProvider);
              if (itemIds.isEmpty) {
                sm.hideCurrentSnackBar();
                sm.showSnackBar(getSnackBar(
                    "Add some data to save the session"));
              } else {
                await ref
                    .read(collectionStateNotifierProvider.notifier)
                    .saveData();

                sm.hideCurrentSnackBar();
                sm.showSnackBar(getSnackBar("Saved"));
              }
            },
      icon: const Icon(
        Icons.save,
        size: 20,
      ),
      label: const Text(
        kLabelSave,
        style: kTextStyleButton,
      ),
),
```
Proposed UI changes
<img width="1440" alt="Screenshot 2024-02-24 at 12 37 41 AM" src="https://github.com/foss42/apidash/assets/111864031/29b0c40d-94ba-40d3-8b96-774aaa13b15b">

**Comment by animator** [comment]
Adding this check is unnecessary and does not add any value for the end user.
