### ISSUE TITLE
[feat] GH-Actions for static code analysis

### ISSUE THREAD

**Issue by opxdelwin** [foss42/apidash#186]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Enable GitHub Actions for this project to automate static Flutter Code Analysis

**Describe the solution/feature you'd like us to add**
Building appropriate pipeline that'd test relevant commits for code analysis issue.

**Any other feedback you would like to provide regarding the site**
A comprehensive discussion must be carried out with the community to fix existing analysis issue, whose fix would be addressed in upcoming PRs. Here are few highlighted analysis issue, for which maintainers may suggest appropriate actions.

<details>
<summary> See Detailed Table </summary>

| Serial No. | Status | Issue |  Location | Suggested Action |
| --- | --- | -------- | ---- | ---- |
| 1. | <ul><li> [ ] </li></ul>| Invalid option specified for 'enable-experiment': Flag "records" is no longer required.| analysis_options.yaml| Remove |
| 2. | <ul><li> [ ] </li></ul>| The parameter type of '==' operators should be non-nullable. Try using a non-nullable type.| lib\models\form_data_model.freezed.dart| Add Lint Ignore|
| 3. | <ul><li> [ ] </li></ul>| The parameter type of '==' operators should be non-nullable. Try using a non-nullable type.| lib\models\name_value_model.freezed.dart ||
| 4. | <ul><li> [ ] </li></ul>| The value of the local variable 'length' isn't used. Try removing the variable or using it.| lib\screens\home_page\editor_pane\details_card\request_pane\request_headers.dart | Remove unused vars |
| 5. | <ul><li> [ ] </li></ul>| The value of the local variable 'length' isn't used. Try removing the variable or using it.| lib\screens\home_page\editor_pane\details_card\request_pane\request_params.dart| Remove unused vars |
| 6. | <ul><li> [ ] </li></ul>| This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method. | lib\widgets\headerfield.dart | Add Annotation |
| 7. | <ul><li> [ ] </li></ul>| This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method. | lib\widgets\json_previewer.dart| Add Annotation |
| 8. | <ul><li> [ ] </li></ul>| Unused import: 'package:apidash/main.dart'. Try removing the import directive. | test\widget_test.dart| For Code Coverage, Fixed in #158  |
| 9. | <ul><li> [ ] </li></ul>| Unused import: 'package:flutter/material.dart'. Try removing the import directive. | test\widgets\markdown_test.dart| Remove imports |
| 10. | <ul><li> [ ] </li></ul>| The variable name '_$$_NameValueModelFromJson' isn't a lowerCamelCase identifier. Try changing the name to follow the lowerCamelCase style. (x2) | lib\models\name_value_model.g.dart | Generated Code, add lint ignore. |
| 11. | <ul><li> [ ] </li></ul>| TODO (x4)| -| Wont break analysis, but better to fix to prevent tech-debt|

</details>

Once we're at par with above mentioned issues, I'll fix them within the main Actions PR itself.

Awaiting everyone's valuable feedback.

**Comment by opxdelwin** [comment]
@ashitaprasad @animator Please share your feedback with reference to serial number..

**Comment by animator** [comment]
It will be added to the roadmap but currently it is not a priority as we have other major features to work on.

**Comment by opxdelwin** [comment]
What if I already have a PR ready :) ?

**Comment by ashitaprasad** [comment]
@opxdelwin Then you can send across a PR. We'll take a look at it.
