### ISSUE TITLE
Double click to maximise/minimise on windows

### ISSUE THREAD

**Issue by zeeshanok** [foss42/apidash#193]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Native windows apps usually have a "double click to maximise/unmaximise the window" feature.

**Describe the solution/feature you'd like us to add**
Double click to maximise/unmaximise.

**Comment by MrunalrajRedij** [comment]
Hey, Can I work on this?

**Comment by animator** [comment]
As API Dash does not have an explicit title bar in Windows, this feature will not be intuitive for (and expected by) the end user.
Hence, closing this issue.
