### ISSUE TITLE
Enhancement: Key Functionality for Header Option Selection

### ISSUE THREAD

**Issue by PCoder23** [foss42/apidash#195]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently, when interacting with the header options in the application, users are unable to utilize the arrow keys to navigate and select options from the list. This enhancement aims to enhance user experience by allowing navigation and selection of header options using the arrow keys. Also , after selecting the option, cursor should move to header value

![Screenshot 2024-02-25 130350](https://github.com/foss42/apidash/assets/85278795/1ae20fcd-1b06-43a6-8989-46d645e5d259)

**Comment by opxdelwin** [comment]
Hey @PCoder23, are you working on the implementation?

**Comment by PCoder23** [comment]
@opxdelwin yes , I am

**Comment by animator** [comment]
It is a nice feature to include. But, kindly resolve https://github.com/foss42/apidash/issues/196 which is of higher priority before proceeding with this issue.

**Comment by PCoder23** [comment]
sure @animator

**Comment by ashitaprasad** [comment]
This issue is now open to be undertaken as #196 has been resolved.

**Comment by PCoder23** [comment]
@ashitaprasad i guess its already resolved with #196

**Comment by ashitaprasad** [comment]
@PCoder23, #196 does not implement the arrow key feature for navigating options in the list, so this issue is still open.

**Comment by PCoder23** [comment]
hey @ashitaprasad , can you confirm this behaviour - control/command + space to open the suggestion box and  and then arrow keys to select the options 

https://github.com/foss42/apidash/assets/85278795/ffdde701-68a7-4fc4-899a-697cebc08e51

or are we expecting some other behaviour

**Comment by animator** [comment]
@PCoder23 Why do you need to press control/command + space
Once the user types a character, the suggestion box automatically opens up.
Now, the user should be able to use up & down arrows to navigate and select an option.

**Comment by PCoder23** [comment]
@animator its for when the user wants to see the all the options of header list, initially when the input is empty and is focused. aside that it will behave as you said

**Comment by animator** [comment]
@PCoder23 send across a PR for review.

**Comment by PCoder23** [comment]
sure

**Comment by ashitaprasad** [comment]
@PCoder23 as you pointed out earlier, this issue has been resolved by #196
