### ISSUE TITLE
Migrated flutter_typeahead to the latest version 5.2.0

### ISSUE THREAD

**Issue by animator** [foss42/apidash#196]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently, API Dash uses flutter_typeahead 4.8.0 that introduced various breaking changes starting 5.0.0
We need to migrate the code base to use the latest version of flutter_typeahead without losing the current functionality

**Comment by andoriyaprashant** [comment]
Hey @animator  I would like to work on this issue, please assign it to me
Thank you

**Comment by ashitaprasad** [comment]
@andoriyaprashant, We do not assign issues. You are free to work on it and send across a PR.
