### ISSUE TITLE
UI Spacing Issue in Settings Screen

### ISSUE THREAD

**Issue by andoriyaprashant** [foss42/apidash#197]
**Describe the bug/problem**
The user interface (UI) elements, specifically ListTile items, in the settings screen are touching each other, causing visual clutter and potential usability issues. This occurs due to the absence of adequate spacing between the ListTile widgets. 

![Screenshot 2024-02-26 010001](https://github.com/foss42/apidash/assets/121665385/7cdae698-5089-4cb3-9869-04f92e2ed172)

**Steps to Reproduce the bug/problem**
The lack of separation between these items can make it challenging for users to distinguish between them and interact with them effectively. To enhance the clarity and usability of the settings screen, it's necessary to introduce proper spacing between the ListTile items to improve the overall visual appearance and user experience.

**Expected behavior**
![Screenshot 2024-02-26 011553](https://github.com/foss42/apidash/assets/121665385/a2a46063-0ff2-43fb-b4f5-0590520604be)

**Device Info (The device where you encountered this issue):**
 - Windows
 - Windows 11
 - chrome

**Comment by Yousef-Rabia** [comment]
The identical issue occurs when hovering over "Save Response."

![image](https://github.com/foss42/apidash/assets/78663127/75bf6e58-9b22-4889-8ed6-b40a13464c7f)
