### ISSUE TITLE
Enhance SVG previewer

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#20]
**Use case**

Currently, the app shows svg as an xml code instead of an image unlike other image formats. 
User should be able to directly view SVG in the response pane when the response is of content type image/svg+xml.

**Comment by Utkarsh4517** [comment]
I want to work on it, can you guide me on this @ashitaprasad

**Comment by ashitaprasad** [comment]
Sure @Utkarsh4517, 
Join our [discord server](https://bit.ly/heyfoss) so that you can message on the **#foss** channel whenever you encounter any issue. That is also our official channel where we have all discussions related to API Dash.
You must also follow the [Contribution Guidelines](https://github.com/foss42/api-dash/blob/main/CONTRIBUTING.md).
Before sending a PR, just let me know when your code is ready for review.

**Comment by Khushal747** [comment]
please assign me this issue under GSSOC'23

**Comment by animator** [comment]
@Khushal747 Please follow the instructions provided by @ashitaprasad [here](https://github.com/foss42/api-dash/issues/20#issuecomment-1555879929).

**Comment by Khushal747** [comment]
ok

**Comment by mmjsmohit** [comment]
Since there hasn't been any activity on this issue since a long time, can I work on this one?

**Comment by animator** [comment]
@mmjsmohit Go ahead man 👍
