### ISSUE TITLE
Alignment issue in search textfield 

### ISSUE THREAD

**Issue by PCoder23** [foss42/apidash#202]
**Describe the bug/problem**
There is an alignment issue with cursor and text in the search textfield in json preview

**Steps to Reproduce the bug/problem**
Hit an api and observe the search texfield in json preview
![Screenshot 2024-02-26 040239](https://github.com/foss42/apidash/assets/85278795/17c3af43-4086-4199-879c-ed0711811e3f)

**Expected behavior**
The cursor should be aligned with text

**Device Info (The device where you encountered this issue):**
 - OS: Windows
 - Version: Windows 11

**Comment by saurav0523** [comment]
@animator  I'll fix this bug

**Comment by animator** [comment]
@PCoder23 Thanks for reporting this issue.
