### ISSUE TITLE
Implement fuzzy string matching to get header suggestions

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#207]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Currently, header suggestions are a sequence of strings which contain the given substring with no logic implemented for ordering. Algorithms like [fuzzy string search](https://redis.com/blog/what-is-fuzzy-matching/) etc. can be used to provide the sequence of matching strings with the most relevant item at the top.

**Comment by opxdelwin** [comment]
Is this still being worked on?

**Comment by animator** [comment]
This issue is still open to work on @opxdelwin 
The issue with the closed PR was the accuracy of results. You can read the thread for more details.

**Comment by PratyushChauhan** [comment]
After reviewing the last PR I have added modifications to improve suggestions.

**Comment by PratyushChauhan** [comment]
@animator are these results good?

Before (no results due to typo):
![image](https://github.com/foss42/apidash/assets/109033080/a742b3d6-ffa3-46c4-8100-79e2a3e87174)


After (using fuzzy match):
![image](https://github.com/foss42/apidash/assets/109033080/079a90ca-80e6-41fe-ad90-6e37702410bb)
