### ISSUE TITLE
Fix response previewer for apng

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#21]
**Use Case**

Currently, the apng shows as a static image instead of an animated image like gif.

**Comment by animator** [comment]
Now works for

https://upload.wikimedia.org/wikipedia/commons/7/7e/Brain_MRI_apng_105px_100ms.png
https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png
