### ISSUE TITLE
Use different structure in PR template for test section

### ISSUE THREAD

**Issue by sebastianbuechler** [foss42/apidash#225]
**Feedback**
Currently, a contributor has to select one of three options regarding "added/updated tests":
![image](https://github.com/foss42/apidash/assets/42775578/d7f27d72-4748-4ee7-b438-478c3d618da7)

However, this format is not optimal, as GitHub understands each option as an open task, and in the PR overview, all PRs will have open tasks, even though they are completed.
![image](https://github.com/foss42/apidash/assets/42775578/3d57b002-4640-48cf-b3b3-44580626cb7c)

**Comment by animator** [comment]
Currently, this format works for us and we ignore the open tasks.
In case you have a better format in mind, you can post it here.

**Comment by opxdelwin** [comment]
The format could be updated so that there isn't a *separate* section to clarify if new tests were written. It could be added as an item under `Checklist`.
![image](https://github.com/foss42/apidash/assets/84124091/9c28634d-83ec-44d3-a626-4b904c91202d)

**Comment by animator** [comment]
@opxdelwin We decided to keep a separate section to clarify if new tests were written as it is important.
Closing this thread as it is not an issue.
