### ISSUE TITLE
Improve code generation for request body of type JSON

### ISSUE THREAD

**Issue by animator** [foss42/apidash#23]
This improvement suggestion was highlighted in #9 

In an app, JSON request body is created based on user input/parameters stored as a Map. This Map is then converted to a string when the request is about to be sent. Our code generator should reflect the same.

**Comment by Uttkarsh-raj** [comment]
hii @animator i would like to work on this issue but can you brief a bit more about it , it would help me  a lot...and can you assign this issue to me...

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant
