### ISSUE TITLE
Fix `intro_message_test.dart`

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#233]
**Describe the bug/problem**
Currently, the test is being skipped due to some error. Fix the test case to make sure it works and remove `skip:true`.
`test/widgets/intro_message_test.dart`

**Comment by Yousef-Rabia** [comment]
Hi @ashitaprasad ,

I hope you're doing well. I wanted to touch base regarding the ongoing issue I'm working on.

Firstly, I've identified a challenge with our use of ```pumpAndSettle``` in the testing process. As per the documentation [here](https://api.flutter.dev/flutter/flutter_test/WidgetTester/pumpAndSettle.html), pumpAndSettle waits for all animations to complete, which leads to an infinite animation loop when used in conjunction with CircularProgressIndicator. To mitigate this, I believe we should transition to using ```pump``` without settle to build frames effectively.

Secondly, within the file ```lib/widgets/intro_message.dart```, I've observed that whenever we call IntroMessage(), we consistently encounter snapshot.connectionState being ConnectionState.waiting. Consequently, this leads to the perpetual display of const ```Center(child: CircularProgressIndicator());```, as illustrated in the attached screenshots.
<br>
![image](https://github.com/foss42/apidash/assets/78663127/4af37b9c-01e6-47bc-805c-6fd942178819)
![image](https://github.com/foss42/apidash/assets/78663127/200022ad-cc97-47ac-a8eb-b9aad1fb1f29)


Could you please provide guidance on resolving this second issue? Your insights would be greatly appreciated.

Thank you for your assistance.

**Comment by animator** [comment]
@Yousef-Rabia The solution is to figure out how to make 
``` dart    
   Future<void> introData() async {
      text = await rootBundle.loadString('assets/intro.md');
      version = (await PackageInfo.fromPlatform()).version;
    }
```
work during testing.
