### ISSUE TITLE
Missing tests for codegen.

### ISSUE THREAD

**Issue by Tanish2002** [foss42/apidash#234]
**Describe the bug/problem**
Currently, the tests for codegen are lackluster. Especially for multipart form requests. There isn't a single test regarding multipart form requests. This makes it easy for bugs and issues to get through testing when adding a codegen for a new language. 

I experienced this firsthand when I was writing codegen for rust libraries. Relevant issue: #160 
We need to include robust tests for codegen, From what I've seen currently multipart forms are the least tested area.

**Comment by sebastianbuechler** [comment]
@Tanish2002 It would also make much sense to run the tests in GitHub Actions, otherwise bugs may not be detected, even though tests are around: https://github.com/foss42/apidash/pull/224

**Comment by Tanish2002** [comment]
@sebastianbuechler, True. However, I do think a pipeline just for running tests is overkill. In my opinion a better solution would be to set up a pre-commit hook. This would remove the hassle of pushing, seeing tests fails, then creating a fixup commit which would pollute the git logs as well.

A pre commit hook simply ensures that tests pass before even pushing.

**Comment by sebastianbuechler** [comment]
@Tanish2002 I do like pre-commit hooks for linting and other smaller tasks. But testing can get quite extensive and can potentially take a couple minutes once test coverage is acceptable. Also, you would lose the ability to commit code that is WIP, as it would often fail tests.

What's the reasoning behind a test pipeline? It can easily be extended for other tasks like linting and static analysis (like I set it up already).

**Comment by Tanish2002** [comment]
> Also, you would lose the ability to commit code that is WIP, as it would often fail tests.

I'm sorry, What I meant was a `pre-push` hook not pre-commit. (Imo making the dev wait 2-3 mins before pushing and running tests should be acceptable).

However, I do get your point, a test pipeline would be useful.

**Comment by animator** [comment]
@Tanish2002 Thanks for raising this issue. We had already identified multipart coverage issue and are addressing it. 
Stay tuned.

**Comment by animator** [comment]
This issue is now resolved.
We now have complete coverage (including multipart) for some codegens (cURL, Python requests, HAR) and the remaining have been raised as separate issues.
Thanks @Tanish2002 🎉
