### ISSUE TITLE
Add CodeGen for C++ (Libcurl)

### ISSUE THREAD

**Issue by mohnishdeshpande** [foss42/apidash#237]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
The code generation feature is missing for C++

**Describe the solution/feature you'd like us to add**
Add CodeGen for C++
Library - libcurl

**Comment by mohnishdeshpande** [comment]
@animator The C++ branch has also been updated (like the C codegen one) with new tests.

**Comment by ashitaprasad** [comment]
Guidelines for adding the codegen - https://github.com/foss42/apidash/discussions/80
