### ISSUE TITLE
Adding codegen for Kotlin using Retrofit

### ISSUE THREAD

**Issue by Photon3009** [foss42/apidash#247]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I want to add a new code generation language for Kotlin using Retrofit. Currently, there is no support for generating code for Kotlin with Retrofit in our system.

**Describe the solution/feature you'd like us to add**
I would like to see support for generating Kotlin code with Retrofit in our code generation system. This would involve creating templates and logic for generating Kotlin code that utilizes Retrofit for making API calls.

**Any other feedback you would like to provide regarding the site**
Overall, I find the site quite useful, but adding support for more new codegen languages would greatly enhance its capabilities and usefulness for developers

**Comment by Photon3009** [comment]
@ashitaprasad @animator please review this!

**Comment by Photon3009** [comment]
Hey @animator, I've updated the test cases to include the example Request Models from POST 4 to POST 9, which were recently added. I've created a new PR (#294) for this issue, as the previous one encountered some complex conflicts after updating with the latest code. Could you please review the new PR?

**Comment by ashitaprasad** [comment]
Guidelines for adding a codegen - https://github.com/foss42/apidash/discussions/80
