### ISSUE TITLE
[bug] Form field disappears partially on long text input

### ISSUE THREAD

**Issue by opxdelwin** [foss42/apidash#250]
**Describe the bug/problem**

When a user types a long sentence into a text field in the body tab's formdata section, half of its vertical spacing is lost, causing the input text to be hidden.

<details>
<summary>Preview</summary>

https://github.com/foss42/apidash/assets/84124091/98887a6a-018e-4d01-a81b-32821062a0b0

</details>

**Steps to Reproduce the bug/problem**
1. Open the app and navigate to the body tab.
2. Go to the formdata section.
3. Select a text field and type a long sentence.

**Expected behavior**
The text field should scroll vertically to accommodate the input text without losing half of its vertical spacing.  
This ensures that the input text remains visible and accessible to the user.

**Device Info (The device where you encountered this issue):**
 - OS: Win10 22H2]

**Comment by animator** [comment]
Reopening the issue as #251 improved the UX but there is still partial clipping of `j`, `p`, `q`, `y` & `g` characters.

![Screenshot 2024-03-09 at 12 47 52 AM](https://github.com/foss42/apidash/assets/615622/4db8101a-bc42-449f-813b-da30f102f8c0)

**Comment by opxdelwin** [comment]
Will look into this soon.

**Comment by opxdelwin** [comment]
I have raised an issue [here] (https://github.com/flutter/flutter/issues/145255) I'll let it run in the background.

I'll be available in full work force after April 23.

Feel free to ping me if anything arises!

**Comment by animator** [comment]
Thanks for the research @opxdelwin 👇 #274 

Setting `isCollapsed: true,` fixes the issue even with default `contentPadding`

| Title | Image |
|------|------|
| No content padding with non-overflow text | ![image](https://github.com/foss42/apidash/assets/84124091/5a181534-def0-4e82-b61c-91059f17a7c7) |
| collapsed true and overflown text without content padding | ![image](https://github.com/foss42/apidash/assets/84124091/20027c8f-ddf9-48ee-ab60-fbcd03f66cd1) |
| collapsed true with overflow and bit content padding (to bring up the underline gap) | ![image](https://github.com/foss42/apidash/assets/84124091/34a563ac-2cc3-4991-9ffb-d34c20349137) |

**Comment by opxdelwin** [comment]
Perfect, looks like it's resolved.
