### ISSUE TITLE
Name of requests pushes the Dashboard down

### ISSUE THREAD

**Issue by dhruvpatidar359** [foss42/apidash#264]
****Describe** the bug/problem**

When ever the length of the request is long , it pushes the dashboard down as follows. 

![image](https://github.com/foss42/apidash/assets/103873587/016fd9f1-0f45-486f-ab1f-570b798df010)

**Steps to Reproduce the bug/problem**
1 ) Create a new request 
2 ) Rename it a big name
3 ) See the magic

**Expected behavior**
The name should be turncated for one line only .

**Device Info (The device where you encountered this issue):**
 - OS: [Windows]
 - Version: [windows 10 ]

**Comment by josephShokry** [comment]
@ashitaprasad  I would like to try to solve this issue can you assign it to me

**Comment by animator** [comment]
Thanks for reporting the issue. It has been resolved in the main branch.
