### ISSUE TITLE
Hyperlinks in responses (Preview mode) should have a ctrl+click shortcut for opening in browser

### ISSUE THREAD

**Issue by morpheus-30** [foss42/apidash#265]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently the user have to copy the link and paste in the browser to open the link.

**Describe the solution/feature you'd like us to add**
It can be improved by either adding a 'open in browser' on right click or ctrl+clicking on the link to open in the browser.

**Any other feedback you would like to provide regarding the site**

**Comment by mohnishdeshpande** [comment]
@morpheus-30 On it!
