### ISSUE TITLE
[feat] Implement Spanish and French Language Support

### ISSUE THREAD

**Issue by opxdelwin** [foss42/apidash#273]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add Spanish and French language support to enhance accessibility and usability.

**Expected Outcome:**
Enhanced accessibility and wider user reach.

**Additional Information:**
Aligns with inclusivity goal and expands user base.

**Implementation**

1. Add language files for Spanish (app_es.arb) and French (app_fr.arb).
2. Integrate `flutter_localizations` package for seamless language switching.
3. Implement language selection feature in settings.
4. Ensure dynamic localization without app restart.

**Comment by PedroFrancoDev** [comment]
@opxdelwin 

Can I contribute to this feature?

**Comment by opxdelwin** [comment]
Hey @PedroFrancoDev a PR is currently active. You may send across your own PR, but the best one would be merged.
