### ISSUE TITLE
Missing code generation language selector

### ISSUE THREAD

**Issue by Tilakraj-B** [foss42/apidash#275]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Whenever a code generation fails, the programming language selector gets hidden and raise issue appears. Every time I have to go to settings and change the language.

**Describe the solution/feature you'd like us to add**
The programming language selector should not be hidden and their should be a retry button in place of copy and download icons so that the user can retry generating code from there.

**Any other feedback you would like to provide regarding the site**
_Your response here_

**Comment by animator** [comment]
Thanks for reporting this issue @Tilakraj-B

**Comment by ashitaprasad** [comment]
The issue has been resolved in the main branch using a fallback URL in case one is missing.
