### ISSUE TITLE
Fix Dart (dio) codegen & tests

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#283]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

dio package API has been updated which is breaking the existing generated codes. 
The task is to update the current Dart (dio) codegen, verify the generated codes and update the test file (don't forget to add new test cases for multipart POST 4-9).

To learn more about codegens check out #80 

See example test script for [Python (requests)](https://github.com/foss42/apidash/blob/main/test/codegen/python_requests_codegen_test.dart) which covers all the test cases.

**Comment by nikkivirtuoso** [comment]
@ashitaprasad as we are fixing the code then we have to update all the test cases for the dart dio right ? including the post testcases

**Comment by ashitaprasad** [comment]
Yes
