### ISSUE TITLE
[Expired]: Invite discord link

### ISSUE THREAD

**Issue by AhmedLotfy02** [foss42/apidash#292]
**Describe the bug/problem**
Discord link is expired

**Steps to Reproduce the bug/problem**
Click on the new link on the readme

**Device Info (The device where you encountered this issue):**
 - OS: [e.g. Windows, MacOS]
 - Version: [e.g. Catalina 10.15.7, Monterey 12.3.1, Windows 11 22H2]
 - Browser (only if you encountered the issue while running the web app): [e.g. chrome, safari]

**Comment by animator** [comment]
Can you kindly share a screenshot of the link on the readme as it is working at our end.

**Comment by AhmedLotfy02** [comment]
@animator 
![image](https://github.com/foss42/apidash/assets/76037906/b1258127-5025-43cc-a500-56e37a74269a)

**Comment by animator** [comment]
Not the screenshot of the discord expired link page.

Can you add the screenshot of the location in the readme page where you clicked.

**Comment by AhmedLotfy02** [comment]
@animator 
![DeepinScreenshot_select-area_٢٠٢٤٠٣١٣٢٠٣٨٥٢](https://github.com/foss42/apidash/assets/76037906/90d01340-3d05-400d-b820-0181c59ad890)

**Comment by AhmedLotfy02** [comment]
Sorry for the confusion it was an bug in my discord as it must be verified first.

**Comment by animator** [comment]
No worries 👍
