### ISSUE TITLE
Missing drag scrolling support in davi package

### ISSUE THREAD

**Issue by DenserMeerkat** [foss42/apidash#299]
**Describe the bug/problem**
The [davi](https://pub.dev/packages/davi) package currently in use to display request params, headers and form data doesn't support drag scrolling (touch) and the package has been dormant for a while.

>**Proposed Solution**
Switch to [data_table_2](https://pub.dev/packages/data_table_2) a more popular and active package and most importantly **supports drag scrolling**.

[repo link - davi](https://github.com/caduandrade/davi_flutter)
[repo link - data_table_2](https://github.com/maxim-saplin/data_table_2)

**Steps to Reproduce the bug/problem**
1. Launch in device with touch input.
2. Attempt to scroll table when params/headers/form data rows overflow available height.

**Expected behavior**
Touch Drag scrolling should work.

**Device Info (The device where you encountered this issue):**
 - OS: Mobile
 - Version: Android 12

**Comment by mdex-geek** [comment]
hey am interested  assigned to me
