### ISSUE TITLE
Protocol selection dropdown

### ISSUE THREAD

**Issue by animator** [foss42/apidash#307]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Required for gRPC (https://github.com/foss42/apidash/issues/14), websockets (https://github.com/foss42/apidash/issues/15), MQTT(https://github.com/foss42/apidash/issues/115), GraphQL (https://github.com/foss42/apidash/issues/117)

Currently, there is no way to switch between different protocols.
![present](https://github.com/foss42/apidash/assets/615622/60f4d4bf-cb8c-42a8-87aa-6649dc1d8b76)

The proposed solution is to add a dropdown button in the space highlighted in the image below.
![proposed](https://github.com/foss42/apidash/assets/615622/adfc5588-e116-4d47-a217-0b7b839849c6)

**Comment by Clasherzz** [comment]
@animator @ashitaprasad  i am not sure but why would you try to include GraphQL with other communication protocols. Like what if  say a user wants to use graphQL query for an websocket connections . The User wont be able able to select both on this drop down menu. I was going through the graphql support issue (#117 ) and i wonder whether apiDash is loooking for a GraphQL that supports HTTP Requests only.
