### ISSUE TITLE
Add a Saving State

### ISSUE THREAD

**Issue by animator** [foss42/apidash#311]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently when the user clicks on the Save button ... The collection is saved and a notification toast is shown. When the collection is large, this process takes some time & the user has no clue what is happening. So for better UX, a dialog with save animation should be displayed while the saving is in progress.

**Comment by AyushTripathi28** [comment]
Hey @animator can you please tell me more about this cause what i see is when I Save any collection one snackbar comes 
<img width="1279" alt="image" src="https://github.com/foss42/apidash/assets/37010915/7a5703c6-ca98-48ce-a10b-7f9829b53a80">

so what type of ux you are expecting here. Please elaborate little bit. 

Thanks
