### ISSUE TITLE
Weird spacing on the settings page

### ISSUE THREAD

**Issue by zTomz** [foss42/apidash#317]
**Describe the bug/problem**
As shown in the following video, the spacing between the `Default URL Scheme` and `Default Code Generator` are weird. Also the hovered ListTile of `Save Responses` overlaps with the Dropdown for the `Default Code Generator`.

https://github.com/foss42/apidash/assets/85431690/13fdbae0-1efb-4eaf-80da-b464d9818f43

**Steps to Reproduce the bug/problem**
Simply go to the settings page.

**Expected behavior**
Better spacing.

**Device Info (The device where you encountered this issue):**
 - OS: Windows
 - Version: Windows 11 22H2

**Comment by animator** [comment]
The issue has been resolved.
