### ISSUE TITLE
bug: overflowing in codegen section

### ISSUE THREAD

**Issue by nikkivirtuoso** [foss42/apidash#329]
**Describe the bug/problem**
when we contract the window of APIDASH the codegen language option overflows. Here is the screen shot:
<img width="894" alt="Screenshot 2024-03-19 at 11 49 02 PM" src="https://github.com/foss42/apidash/assets/148634283/179f51f3-9cce-450c-8329-c525a24a8e11">

**Steps to Reproduce the bug/problem**
simply decrease the width of application

**Device Info (The device where you encountered this issue):**
 - OS: [e.g. Windows, MacOS]
 - Version: [e.g. Catalina 10.15.7, Monterey 12.3.1, Windows 11 22H2]
 - Browser (only if you encountered the issue while running the web app): [e.g. chrome, safari]

**Comment by animator** [comment]
Caused due to `Java (asynchttpclient)`
