### ISSUE TITLE
Opening Requests Results in No Action

### ISSUE THREAD

**Issue by Yousef-Rabia** [foss42/apidash#341]
**Describe the bug/problem**
When attempting to open any request, it do nothing.

https://github.com/foss42/apidash/assets/78663127/b08b9375-d3c8-4a4f-8485-7e15b53705e1

**Expected behavior**
Open Request Screen 
**Device Info (The device where you encountered this issue):**
 - OS: Android
 - Version: Android 14

**Comment by ashitaprasad** [comment]
The app is currently not available on Android/iOS. 
You can follow this issue https://github.com/foss42/apidash/issues/33 to see the progress that is being made.
