### ISSUE TITLE
Add code generators for different programming languages (python, javascript, kotlin, etc.)

### ISSUE THREAD

**Issue by animator** [foss42/apidash#35]
**Objective**
Currently, API Dash generates code for Dart language (using `http` package).
We should add more code generators for different languages like javascript, python, kotlin, etc. 
Also, supporting different libraries for the same language like `dio` for Dart. 

**Location in the project**
`lib/codegen/`

**How to contribute**

**Step 1** - Choose a language and/or library for which you want to add the code generator.  
**Step 2** - Create a new issue with title `Adding codegen for <language> using <library>`.
**Step 3** - Send a PR with the changes. In the description mention the issue you raised in **Step 2**.

**Comment by PravanshuSamadhiya** [comment]
I want to Work on this Please Assign this issue to me

**Comment by animator** [comment]
@PravanshuSamadhiya All further instructions are already provided in the issue description.

**Comment by mmjsmohit** [comment]
Can I also work with @PravanshuSamadhiya concurrently on this issue so that we may both divide the workload and implement more languages to the code generator.

**Comment by animator** [comment]
@mmjsmohit you can definitely refer to the open source codes in the specified repo. But, instead of copying it as is, a better way is to understand it and implement it in dart in our repo. 

I am not sure if @PravanshuSamadhiya is working on this issue as he has not raised any issue indicating that he is working on any language/library code generator so far.

**Comment by animator** [comment]
Kotlin support has now been added by @mmjsmohit in PR #53 🎉

**Comment by shrey-a-gupta** [comment]
hey @animator I am willing to work on this Issue. I am a beginner in Dart and Flutter.

**Comment by animator** [comment]
Hi @shrey-a-gupta you can choose a programming language and follow the steps mentioned [here](https://github.com/foss42/api-dash/issues/35#issue-1719367303).
Also, do take a look at [FAQs & Getting Started Guide for GSSoC students](https://github.com/foss42/api-dash/discussions/45).

**Comment by animator** [comment]
Migrated to discussion - https://github.com/foss42/apidash/discussions/80
