### ISSUE TITLE
Fix textfield issue for large number of URL params, Headers or Form data body

### ISSUE THREAD

**Issue by animator** [foss42/apidash#350]
After adding a lot of rows, whenever a new row gets added in URL Params, Headers or Form data body, the current textfield loses focus & the table scrolls to the top making it inconvenient for the user.

**Comment by alainjr10** [comment]
The issue seems to be coming from the davi package 
See: https://github.com/caduandrade/davi_flutter/issues/84
Maybe we can edit the package itself? and then implementat on apidash
