### ISSUE TITLE
Saving state never terminates if persistent files cannot be accessed / modified

### ISSUE THREAD

**Issue by AcousticDeveloper** [foss42/apidash#359]
**Describe the bug/problem**
To store data API Dash requires 4 files, namely - 
1. apidash-data.hive
2. apidash-data.lock
3. apidash-settings.hive
4. apidash-settings.lock

Now in Windows, these files are generated inside `%USERPROFILE%/Documents` directory and in Linux, these are generated under `~/` directory. If these locations are protected, i.e. external programs cannot create files in these locations or modify existing files, then if API Dash tries to access these files, it throws an error and the UI never updates. 

**Steps to Reproduce the bug/problem**
Reproducing this issue can be achieved via many ways, i.e. revoking write access to the generated files and trying to save a request. A simpler way to reproduce this issue on Windows is to enable Ransomware Protection which will disallow external programs trying to generate files under some predefined directories (`%USERPROFILE%/Documents` being one of them) and then trying to save a request.

After clicking `save`, the saving state never terminates.

![Screenshot 2024-03-25 154145](https://github.com/foss42/apidash/assets/161834431/3e4c1610-7dcc-4335-8086-935e3930f587)

API Dash throws error in the terminal stating it cannot access the files user to store persistent data.

![Screenshot 2024-03-25 153740](https://github.com/foss42/apidash/assets/161834431/ab1ab8ae-77a3-436a-b38c-637142d04902)

**Expected behavior**
User should be presented with an error message stating that the respective files could not be read / modified and file permissions needs to be updated by the user. 

An enhancement to the solution is to add a default location for persistent data and then give the user ability to load data and settings from custom location using file path. This will allow users to version control request templates and share the existing requests among developers.

**Device Info (The device where you encountered this issue):**
 - OS: Windows 11

**Comment by Tanish2002** [comment]
@animator what would we want here? Do we need a popup(stating the directory is read-only) or exit the app if files cannot be accessed? 

The former might be tricky since hive is initialized before the actual flutter app, so I will have to prop drill this info to the actual app.

**Comment by AcousticDeveloper** [comment]
@Tanish2002 During my specific encounter to the issue, the app did not open while the files weren't created. Thus if the files aren't available at all, then an error window should notify the user that required files cannot be created. But in case the files were available (read access given, no write access) then the core functionality of sending requests is working, thus closing the application is not the solution, in that case an error message can be shown if the user tries to save the state, stating that write permission is required.

> @animator what would we want here? Do we need a popup(stating the directory is read-only) or exit the app if files cannot be accessed?

**Comment by animator** [comment]
Adding to what @Tanish2002 suggested. This should be the desired flow:
- When the user opens the app for the first time he/she should be prompted to choose a folder where the data will be stored.
- A quick write (hive initialization) is then performed in this location to check if proper write permissions are in place. In case of any error, the user is prompted to choose a new location and notified of the permission issue.
- This location (key: value) has to be stored somewhere (like shared preferences) to which the app always has the access. 
- As this location is now established, the next time the app is opened, hive uses this path for initilization.
- User have the option to change this path from Settings.

**Comment by Sarath191181208** [comment]
Hi guys, 
I am a newbie in flutter, but I still want to make a positive contribution and wanted to contribute towards this issue. 
I worked on this a little bit and created something like this: 
```dart 
  // main.dart
  runApp(
    const HiveDirectorySelector(
      child: ProviderScope(
        child: DashApp(),
      ),
    ),
  );

```

```ruby
# hive_directory_selector.dart pseudo code
HiveDirectorySelector StatefulWidget
    build()
        FutureBuilder
            future: getHiveSaveFolder(), # loads from shared preferences
            builder: (BuildContext ctx, AsyncSnapshot<String?> snapshot)
                if (snapshot.connectionState != ConnectionState.done)
                    return CircularProgressIndicator();
                
                if (snapshot.data == null)
                    selectFolder();
                    CircularProgressIndicator();
                
                return widget.child;
    
    selectFolder()
        selectedDirectory = await FilePicker.platform.getDirectoryPath();
        if (selectedDirectory != null)
            setHiveSaveFolder(selectedDirectory); # saves to shared preferences
            setState(() {});
```

**Comment by ashitaprasad** [comment]
@Sarath191181208 Can you please raise a PR. It is much easier to execute and review.
