### ISSUE TITLE
UI update for API Dash Website 

### ISSUE THREAD

**Issue by yashas-hm** [foss42/apidash#362]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
The api dash website has some minor UI issue like: 
- UrlPathStrategy should be used instead of UrlHashStrategy for the website url
- Shadow behind the preview images are hazy and its not looking good. 
- Features list should have containers of similar sizes(current they are wrapped to text size). 
- Clicking on nav icons should animate scroll to the desired view. 
- Theme colors do not match api dash.

**Describe the solution/feature you'd like us to add**
I would like to fix all the issues and add a dark mode switch for the website.

**Comment by ashitaprasad** [comment]
Thanks for your feedback. Modifying the landing page is currently not a priority for the project.
