### ISSUE TITLE
Adding Hover effect on Buttons and fixing and align the Nav bar

### ISSUE THREAD

**Issue by Vineetg2003** [foss42/apidash#37]
Hello 
I have an extraordinary skills to make website more attractive . I will make your website user friendly I will add these features:
Add Hover effect on button
Fixing and align attractive Nav bar ,sign in and up
And apply best background effect.
Please assign these issue under GSSOC'23.

Thank You

**Comment by animator** [comment]
@Vineetg2003 API Dash is a cross platform app and not a website.
