### ISSUE TITLE
Incorrect initial request name in top bar

### ISSUE THREAD

**Issue by mmjsmohit** [foss42/apidash#371]
**Describe the bug/problem**
The default name of a request is not displayed in the top bar.
![image](https://github.com/foss42/apidash/assets/65406090/0a2efe3a-5aa2-437a-9165-1115c3a15903)

**Steps to Reproduce the bug/problem**
Create a new request by clicking on the new button. The top bar is empty without the text **untitled**.

**Expected behavior**
It should display _**untitled**_ as it's the default request name and change whenever the request is renamed.

**Device Info (The device where you encountered this issue):**
 - OS: Ubuntu
 - Version: 23.04

**Comment by opxdelwin** [comment]
Well, in my opinion, it'd be appropriate to show "New Request" over "untitled". Any reason you're sticking with "untitled"

**Comment by animator** [comment]
Not an issue because untitled in the request card is just a placeholder and gets replaced by the URL as soon as the user starts typing it. The name displayed above the URL card is the actual name entered by the user which is optional and empty to begin with.

**Comment by opxdelwin** [comment]
@animator, I was suggesting to replace the blank with "New Request" for actual name of the request, which is right over the URL Card
