### ISSUE TITLE
Automatic Request History and Management

### ISSUE THREAD

**Issue by salahu01** [foss42/apidash#384]
Currently, Api Dash requires users to manually save each API request. This can be cumbersome, especially when working with multiple requests or iterating through different configurations.  Postman, a popular API testing tool, offers automatic request history with the ability to name and organize requests for easier access and reference.

Implementing automatic request history and management in Api Dash would significantly improve its usability. This feature could include:

* Automatically saving past API requests with timestamps.
* Allowing users to name and organize saved requests for better management.
* The ability to filter and search through saved requests.

This functionality would make Api Dash a more efficient and user-friendly tool for developers and testers working with multiple APIs.

**Comment by animator** [comment]
Thank you for your feedback. I have added your comments to the original thread for this feature - https://github.com/foss42/apidash/issues/184#issuecomment-2075218364
Closing this issue as a duplicate, but I will update the progress of this feature in this thread once it is live.
