### ISSUE TITLE
Setting up GitHub Actions for CI and CD

### ISSUE THREAD

**Issue by NotAProton** [foss42/apidash#387]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
If we use Github Actions: 
1) The compilation and uploading of binaries, which is currently done manually by maintainers at release, can be automated. This will increase transparency and reproducibility of builds.
2) CI: Github actions can run tests automatically at every commit and on every PR. 

**Describe the solution/feature you'd like us to add**
Use github actions to for CI/CD

**Any other feedback you would like to provide regarding the site**
We can release tarballs for linux users who don't use rpm or deb supporting distros to run API Dash easily. (https://github.com/foss42/apidash/discussions/240#discussioncomment-8650009 by @Tanish2002). This will also make packaging for flatpak easier.

**Comment by ashitaprasad** [comment]
Closing this issue as we already have a GitHub discussion with the task that must be undertaken first provided [here](https://github.com/foss42/apidash/discussions/240#discussioncomment-8650003).
