### ISSUE TITLE
Add automated workflows for greetings, autolabel, etc

### ISSUE THREAD

**Issue by aindree-2005** [foss42/apidash#398]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I would like to use github actions to design a workflow for automated greetings when user makes PR, raises issue,etc

**Describe the solution/feature you'd like us to add**
Use github actions

**Any other feedback you would like to provide regarding the site**
N/A

**Comment by ashitaprasad** [comment]
We don't need it as we actively engage with our contributors.
