### ISSUE TITLE
workflows for auto commenting 

### ISSUE THREAD

**Issue by MohanRamSridhar** [foss42/apidash#405]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Users are lately notified and mail is only sent once the PA or someone comments on the issue our PR

**Describe the solution/feature you'd like us to add**
I would like to create a workflow that will auto comment on issues and will also auto comment once a PR is opened or closed or merged

**Comment by MohanRamSridhar** [comment]
please assign this task to me under gssoc

**Comment by ashitaprasad** [comment]
Please read the contributing guide to understand the project requirements.
