### ISSUE TITLE
Unknown Response Content-Type - null. 

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [foss42/apidash#415]
**Describe the bug/problem**
I made simple request right after building apidash just to test it out aaaaaand i got "Unknown Response Content-Type - null. " which might be caused because of the very simple http server i was asking, not setting content-type. curl command itself executes without issue so its purely apidash issue.

**Steps to Reproduce the bug/problem**
Probably just send request to server that won't return content type

**Expected behavior**
it should display response, in my case json, like its nothing.

**Device Info (The device where you encountered this issue):**
 - OS: opensuse Tumbleweed but i don't think it matters
 - Version: master at the time of writing 806a72de4b35155c44b7db0955c0d92db1daccda
 - Browser (only if you encountered the issue while running the web app): nope

**Comment by ashitaprasad** [comment]
Hi @Michal-Szczepaniak Can you do `flutter clean` and build it again .. It should get resolved.

**Comment by Michal-Szczepaniak** [comment]
Still same issue :/

**Comment by ashitaprasad** [comment]
Can you click on `Headers` and share the screenshot as shown below 
![Screenshot 2024-06-27 at 10 58 32 PM](https://github.com/foss42/apidash/assets/1382619/a5536c46-098c-4460-9b9f-3eef015fe923)

**Comment by Michal-Szczepaniak** [comment]
![Screenshot_20240627_203207](https://github.com/foss42/apidash/assets/11545014/b68b049f-f28c-4390-81fe-15bff9726e8c)

**Comment by ashitaprasad** [comment]
Thanks for the screenshot.
The error is due to null content type.
We will add a fix to handle such cases and close this issue once it is live.

**Comment by Michal-Szczepaniak** [comment]
ye literally what i said :D

**Comment by ashitaprasad** [comment]
@Michal-Szczepaniak 😂

**Comment by Michal-Szczepaniak** [comment]
@ashitaprasad is there roadmap somewhere? There are two features im eagerly waiting for
