### ISSUE TITLE
Add Support for Syntax Highlighting of .env Files

### ISSUE THREAD

**Issue by pgsohail** [foss42/apidash#447]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently, API Dash doesn't offer syntax highlighting for .env files, which are commonly used in many projects for environment variables. Adding this feature would improve readability and help developers quickly identify key-value pairs within .env files.
**Describe the solution/feature you'd like us to add**
Implement syntax highlighting for .env files with a focus on key-value pairs, comments, and special characters.
Ensure compatibility with different variable formats used across projects.
**Any other feedback you would like to provide regarding the site**
Benefits:
Enhanced developer experience by improving the visibility of important environment variables.
Aligns with API Dash's goal to support a wide range of file types and enhance developer productivity.

**Comment by ashitaprasad** [comment]
This feature is not relevant for an API client as it is not an IDE.
