### ISSUE TITLE
Add options for formatted "json" in the API response.

### ISSUE THREAD

**Issue by TheCodeDaniel** [foss42/apidash#462]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
So i called an API, and the only format to view the API response were "Preview" and "Raw" , i wanted to also see the response in Json format, just like postman

**Describe the solution/feature you'd like us to add**
I would recommend adding an option for "json" under the body response

**Any other feedback you would like to provide regarding the site**
The software is really nice, this is just me suggesting way it could be better.
![WhatsApp Image 2024-09-05 at 08 11 35](https://github.com/user-attachments/assets/3a070182-af16-42ce-a6e1-46a9aa9ede2b)

**Comment by TheCodeDaniel** [comment]
look a the screenshot, after "Preview and Raw" under "Body", im suggesting it could be "Preview, Raw and Json".

truth be told, this feature isn't a blocker, the preview gives me a more detailed layout than even a regular formatted json response and then i can copy the API response under the "Raw" section,

Maybe anyone can tell me how they also feel about this feature

**Comment by ashitaprasad** [comment]
Thanks for your feedback @TheCodeDaniel 
We have created "Preview" (tree layout with search) such that it is easier to navigate JSON.
We tried formatting JSON in the past, but without syntax highlighting it was not giving a good experience and with syntax highlighting the rendering performance was very bad (Flutter limitation), hence the tree previewer was used.

**Comment by ashitaprasad** [comment]
Also, we have added the feature where when you press the download or copy button, the formatted response gets downloaded or copied that you can browse using your favourite editor.

**Comment by TheCodeDaniel** [comment]
Thanks for clarifying @ashitaprasad ,  i really appreciate the feedback.
I actually plan to make a switch from postman to API dash for regular endpoint testing, 
I would also want to contribute in some way to this project.

**Comment by ashitaprasad** [comment]
Nice @TheCodeDaniel :)
You can surely pick up any open good first issue and contribute to the project.

**Comment by shivam-jainn** [comment]
Can I work on this issue?

**Comment by ashitaprasad** [comment]
Closing this issue based on my comment above. Thanks.
