### ISSUE TITLE
Issue while selecting directory

### ISSUE THREAD

**Issue by userAdityaa** [foss42/apidash#472]
Description: When attempting to select a directory in the API Dash interface, the option for selecting a directory is not available. Additionally, the field or dialog that allows users to manually enter or select a directory path is not taking any word. This issue restricts users from specifying a directory, which is crucial for certain API functionalities.

#### Steps to Reproduce the bug/problem
- Setup the project following the contributors guideline.
- flutter run to run the project.
- The interface for apidash will be shown.
- Now click on selecting the directory

#### Expected behavior
- We should be able to give input in textarea or tap select to check the directory.

#### Device Info 
 - MacOS
 - Version: Sequoia 15.0

#### Flutter Doctor
<img width="1267" alt="Screenshot 2024-09-30 at 3 29 05 AM" src="https://github.com/user-attachments/assets/a932556c-e857-4d00-9b25-055b1e6baa6a">
<img width="1440" alt="Screenshot 2024-09-30 at 3 30 36 AM" src="https://github.com/user-attachments/assets/0f290fd1-5e95-49bf-9b9c-1220e7e74aac">

Issue: 
https://github.com/user-attachments/assets/5c23250e-14a2-47e9-bbb6-96c66ca49d0f

**Comment by ashitaprasad** [comment]
Looks like you haven't added the `com.apple.security.files.user-selected.read-write` entitlement as mentioned in the [here](https://github.com/foss42/apidash/blob/main/doc/dev_guide/platform_specific_instructions.md).
It was mentioned in the Contributing Guidelines.
Please check and confirm again.

**Comment by userAdityaa** [comment]
Yes, I forgot to put this part. Thanks for the help.
