### ISSUE TITLE
Open the context menu with the right click

### ISSUE THREAD

**Issue by ClementBeal** [foss42/apidash#476]
#### Feedback
In the request or variable pages, we've got a list of requests and variable environments.

In order to make an action (duplicate, remove etc...), we have to press the trailing button. The button is very small and it requires a bit of precision to press it.

It could be better if with a right click on the list item, we open the menu.

**Comment by ashitaprasad** [comment]
Thanks for raising this issue. It is definitely a good suggestion.

**Comment by Rajkdea123** [comment]
Can you pls assign this issue to me?

**Comment by ashitaprasad** [comment]
@Rajkdea123 we do not assign issues until we receive a draft PR which works towards a potential fix.
