### ISSUE TITLE
Url not initializing when clicking the sidebar "add" button

### ISSUE THREAD

**Issue by FreeBono** [foss42/apidash#479]
#### Describe the bug/problem
When I click the "add" button to create a new "request", the url of texteditor remains the same, but the url of requestmodel for the actual id seems to be "".

#### Steps to Reproduce the bug/problem
_Please provide the steps to reproduce the behaviour. Screenshot(s)/image(s) are preferred to help explain it better_

#### Expected behavior
I think url text state would be a same with requestmodel url of selectedId.

#### Device Info (The device where you encountered this issue)
 - OS: windows
 - Version: 0.4.0

https://github.com/user-attachments/assets/72c8c577-a91f-4fb5-ae92-98be017fdb25

#### Flutter Doctor
Please run the `flutter doctor -v` command and provide the details below:

```
<insert flutter doctor output here>
```

**Comment by ashitaprasad** [comment]
Thank you for reporting this issue. We will investigate it further.
