### ISSUE TITLE
Add ability to send https requests without SSL verification

### ISSUE THREAD

**Issue by pacnpal** [foss42/apidash#486]
#### Tell us about the task you want to perform and are unable to do so because the feature is not available
Unable to send https requests to servers that don't have certificates, such as local IP addresses

#### Describe the solution/feature you'd like us to add
Add function for curl request to be sent with the -k option, ignoring the certificate verification step

**Comment by ashitaprasad** [comment]
Thank you for raising the issue. This is definitely a useful feature.
Also, a good issue on which people can contribute.

**Comment by nilaygit-10721** [comment]
can you assign me this issue?

**Comment by ashitaprasad** [comment]
@nilaygit-10721 We do not assign any issues. Anyone can work on the issue and submit a PR.

**Comment by Clasherzz** [comment]
@ i would love to work on this since i myself faced this issue while working on adding codgen for hyper.
My approach and changes would be:
-> adding a toogle button in settings for ssl certificate verification (by default its turned on.)
-> changing settings model and adding a provider for ssl.
-> make a custom http client that can make requests without checking for ssl certificates and use that client when ssl certification is turned off.

**Comment by ashitaprasad** [comment]
@Clasherzz Can you share how the custom client will look in this thread.

**Comment by ashitaprasad** [comment]
@Clasherzz What about multipart request?

**Comment by Clasherzz** [comment]
> @Clasherzz What about multipart request?
i havent checked on that yet since i couldnt find a way to test that . But i can set up my own development enviornment and try that. I am pretty sure that it wont be a problem though since all i am adding is a callback to handle bad ssl

**Comment by Clasherzz** [comment]
> @Clasherzz What about multipart request?

@ashitaprasad i would try parsing the multipart request made to the custom client
```
void main() async {
  Uri uri = Uri.parse("https://localhost:3443/upload");
  http.Client client = createHttpClientWithNoSSL();

  try {
    var request = http.MultipartRequest("POST", uri);

    request.fields['field1'] = 'value1';
    request.fields['field2'] = 'value2';


  
    var streamedResponse = await client.send(request);

   request.files.add(await http.MultipartFile.fromPath(
      'file',
      'C:/Users/HP/Downloads/DBMS',
    ));
    var response = await http.Response.fromStream(streamedResponse);

    print("Response status: ${response.statusCode}");
    print("Response body: ${response.body}");
  } catch (e) {
    print("Error: $e");
  } finally {
    client.close();
  }
}

```
this was tested on the upload endpoint in local system(code : https://github.com/Clasherzz/testing)

**Comment by Clasherzz** [comment]
> > @Clasherzz What about multipart request?
> 
> @ashitaprasad i would try parsing the multipart request made to the custom client
> 
> ```
> void main() async {
>   Uri uri = Uri.parse("https://localhost:3443/upload");
>   http.Client client = createHttpClientWithNoSSL();
> 
>   try {
>     var request = http.MultipartRequest("POST", uri);
> 
>     request.fields['field1'] = 'value1';
>     request.fields['field2'] = 'value2';
> 
> 
>   
>     var streamedResponse = await client.send(request);
> 
>    request.files.add(await http.MultipartFile.fromPath(
>       'file',
>       'C:/Users/HP/Downloads/DBMS',
>     ));
>     var response = await http.Response.fromStream(streamedResponse);
> 
>     print("Response status: ${response.statusCode}");
>     print("Response body: ${response.body}");
>   } catch (e) {
>     print("Error: $e");
>   } finally {
>     client.close();
>   }
> }
> ```
> 
> this was tested on the upload endpoint in local system(code : https://github.com/Clasherzz/testing)

@ashitaprasad does this look good ?

**Comment by ashitaprasad** [comment]
@Clasherzz Thanks for sharing the approach. Looks good, but we recently decided to put a hold to any http_service changes as we are planning to migrate to `dio` from `http`.

**Comment by Clasherzz** [comment]
> @Clasherzz Thanks for sharing the approach. Looks good, but we recently decided to put a hold to any http_service changes as we are planning to migrate to `dio` from `http`.

**Comment by Clasherzz** [comment]
@ashitaprasad i see.

**Comment by ashitaprasad** [comment]
@Clasherzz kindly take a look the [Roadmap](https://github.com/foss42/apidash/blob/main/ROADMAP.md) which now provides the project priorities and review timelines.

**Comment by ashitaprasad** [comment]
Hi @pacnpal This feature is now available in API Dash.
You can check out the doc - https://github.com/foss42/apidash/blob/main/doc/user_guide/disable_ssl.md to learn more about how to use this feature.
