### ISSUE TITLE
Issue: Lack of Support for URL Scheme Without HTTP/HTTPS Prefix 

### ISSUE THREAD

**Issue by userAdityaa** [foss42/apidash#487]
### Tell us about the task you want to perform and are unable to do so because the feature is not available

I want to test APIs on my local server using the URL format localhost:3000 (without http://). Currently, API Dash does not support this format and returns an error, making it inconvenient to test APIs locally without explicitly adding the http:// prefix.

### Describe the solution/feature you'd like us to add

Add support for URLs using the localhost:3000 format, allowing users to enter URLs without needing the http:// scheme prefix. This feature would streamline the testing process by accepting both localhost:3000 and http://localhost:3000 as valid inputs, similar to how tools like Postman handle local URLs.

### Any other feedback you would like to provide regarding the site

API Dash is a great tool for testing APIs, and adding this small but useful feature would further enhance usability, especially for developers working in local development environments. Thank you for considering this improvement!

### Screenshot of the issue
<img width="361" alt="Screenshot 2024-11-01 at 5 16 15 AM" src="https://github.com/user-attachments/assets/7c3c6b5c-7f3f-44a1-83f9-d2af9a5e6315">
<img width="529" alt="Screenshot 2024-11-01 at 5 16 26 AM" src="https://github.com/user-attachments/assets/1645361f-30ff-4c95-8ddb-1b3a0e5ef3a3">

**Comment by ashitaprasad** [comment]
@userAdityaa Thanks for reporting. Yes this support will be useful.
