### ISSUE TITLE
macOS: Missing Guide for File Access Permissions in dev_guide/setup_run.md

### ISSUE THREAD

**Issue by imukulgehlot** [foss42/apidash#494]
#### Feedback

There is no guide on how to add the necessary permissions in [doc/dev_guide/setup_run.md](https://github.com/foss42/apidash/blob/main/doc/dev_guide/setup_run.md) for accessing files or directories outside the app’s sandboxed environment. This is required for selecting a workspace once the API Dash is launched.

**Comment by imukulgehlot** [comment]
### **Response to Feedback: macOS: Missing Guide for File Access Permissions in `setup_run.md`**

Following the steps in [setup_run.md](https://github.com/foss42/apidash/blob/main/doc/dev_guide/setup_run.md), I was able to launch API Dash on macOS after creating the platform-specific folder and running the Melos command. However, I couldn't select a workspace because `getDirectoryPath` couldn’t access directories outside the sandbox.

To resolve this, I had to add the following to `macos/Runner/DebugProfile.entitlements`:

```xml
<key>com.apple.security.files.user-selected.read-write</key>
<true/>
```
It seems this step should be included in the setup guide, specifically in step 4 for macOS users, as it was missing from the default entitlements.

PS: Apologies for missing the platform-specific instructions - this permission seems necessary for macOS setup.

I’m closing this issue/feedback now as resolved.

**Comment by ashitaprasad** [comment]
@imukulgehlot Actually it is a valid issue ... the setup instructions should have clearly stated that before flutter run.
Please go ahead and send across a PR modifying the setup instructions by informing the users that they need to follow platform-specific instructions.
