### ISSUE TITLE
MacOS Installation Roadblock and Adding APIDash Project on Melos

### ISSUE THREAD

**Issue by StormGear** [foss42/apidash#517]
#### Feedback
When installing the macOS distributable there could potentially be a roadblock that is not treated in the installation guide. This is a screenshot of what I mean.
<img width="664" alt="Screenshot 2024-12-13 at 10 56 28 AM" src="https://github.com/user-attachments/assets/ee20a05e-1177-414b-861b-af6866ca2c44" />
In this screenshot, it does not immediately give an option to "open anyway" as the installation guide shows. One has to go an additional step into the settings of their macOS in order to have it installed. I would like to add this `installation instructions` to the guide.

Also, APIDash uses melos. On the melos page on [pub.dev](https://pub.dev/packages/melos#who-is-using-melos) there is a list of projects that make use of melos, however I noticed that the APIDash project is not among that list. I felt the need to point it out, and to see if this project could be added to their list which could potentially increase visibility as well as Open-Source Contributions.

**Comment by ashitaprasad** [comment]
Although we have covered all the steps in the macOS installation guide. Still if you find something missing. You can send a PR.
https://github.com/foss42/apidash/blob/main/INSTALLATION.md#macos

API Dash is already listed in melos page in the main repo - https://github.com/invertase/melos/tree/main/packages/melos
It will reflect on pub.dev once the next version of melos is released.
