### ISSUE TITLE
Improving User Experience: Relocating the "+ Add Parameter" Button and Introducing Checkbox Functionality for Parameter Management

### ISSUE THREAD

**Issue by sherazahmad720** [foss42/apidash#58]
To optimise the user experience when working with parameters in application, I propose the following suggestions:

Relocating the "+ Add Parameter" Button: Currently positioned at the bottom of the page, the button requires users to go down to the screen, which can be inconvenient, especially for users with portrait screens. To address this issue, we recommend relocating the button to a more accessible position below the parameter fields. This adjustment allows users to add new parameters without going down to the screen again and again.

Automatic Row Addition: Additionally, we suggest introducing an automatic row addition feature to simplify parameter input. Instead of relying solely on the "+ Add Parameter" button, users can start typing in a single text field located above the parameter list. As they type, a new empty row will automatically be added below, facilitating the effortless addition of new parameters. This streamlines the process and eliminates the need for users to manually click the button for each new parameter.

Checkbox Functionality for Parameter Management: Furthermore, I recommend incorporating checkboxes before each parameter. This feature empowers users to easily enable or disable specific parameters when testing their API. By checking or unchecking the corresponding checkbox, users can conveniently include or exclude specific parameters. This functionality provides greater flexibility and customization options for API testing.

For visual reference, please refer to the attached photo.

![Desktop - 1](https://github.com/foss42/api-dash/assets/65251002/b164546d-63c1-4e09-bf2d-a78cebdbf077)

By implementing these suggested enhancements, we significantly enhance the user experience by reducing navigation efforts, streamlining parameter management, and providing a more intuitive and flexible application.

**Comment by animator** [comment]
Hi @sherazahmad720 
Thank you for your wonderful suggestions. We definitely add these features to our roadmap.

**Comment by sherazahmad720** [comment]
@animator i can do this if you want

**Comment by animator** [comment]
Sure @sherazahmad720 please feel free to work on this issue. As you suggested, a new empty row that automatically gets added below is the most intuitive way to go. Also checkbox functionality will also be very useful for API testing.

**Comment by sam-shot** [comment]
Can I work on this??

**Comment by animator** [comment]
Sure @sam-shot !

**Comment by AbhinavISM** [comment]
Hi sir, I was thinking about solving this problem, one way seems to be using records to show multiple types of rows using DaviModel<(NameValueModel, RequestParamCustomisationEnum)> instead of DaviModel<NameValueModel> and then we can add custom rows to our model, enums for which exist in RequestParamCustomisationEnum.

Another way can be stop using NameValueModel here altogether and create a class UrlParamsModel which would have a member of class NameValueModel as well as RequestParamCustomisationEnum with an either or fashion.

Are there better ways I should figure out? or should I continue with one of those?

I apologize if I am asking for too much, I am thinking to prefer the second method, as it seems cleaner.

**Comment by ashitaprasad** [comment]
**Introducing Checkbox Functionality for Parameter Management** has now been merged (#97) so it is no longer an issue and is being removed from the title of this issue.

**Comment by animator** [comment]
Buttons feature is now being tracked in https://github.com/foss42/apidash/issues/304
