### ISSUE TITLE
Adding codegen for Python using Request.

### ISSUE THREAD

**Issue by Mixel2004** [foss42/apidash#64]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Generate API Request code in Python using the code generator feature.

**Describe the solution/feature you'd like us to add**
Add Python Code Generator using Request library 

**Any other feedback you would like to provide regarding the site**
No

**Comment by Saimurugeshwari** [comment]
can i work on this issue under GSSOC23

**Comment by animator** [comment]
@Saimurugeshwari you can work on any other codegen which is currently not available. Check out https://github.com/foss42/api-dash/issues/35 for more details.
