### ISSUE TITLE
Adding Find box

### ISSUE THREAD

**Issue by resfandiari** [foss42/apidash#79]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I want to search for characters, text, and phrases on the body preview or raw page.

**Describe the solution/feature you'd like us to add**
Adding find box.

**Comment by animator** [comment]
Thank you for your valuable suggestion. This feature will be really useful.
We have added it to our roadmap. 
Also, please feel free to send a PR.

**Comment by animator** [comment]
This issue has been resolved and merged in the main branch. 
The issue will be closed with the next release of API Dash.

**Comment by animator** [comment]
It is now available in the latest release of API Dash ⚡️
