### ISSUE TITLE
[Windows] Hide/custom title bar like in macOS

### ISSUE THREAD

**Issue by damywise** [foss42/apidash#89]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Increases space for app by roughly 30 pixels vertically

**Describe the solution/feature you'd like us to add**
Add custom title bar, since you are already using `window_manager` anyway, why not also Windows?

**Any other feedback you would like to provide regarding the app**
What I think the app would roughly look like
![temp_](https://github.com/foss42/apidash/assets/25608913/7bec79db-8a07-4cc5-a12e-f9c4ce282b47)

**Comment by damywise** [comment]
Ah, I guess on Windows you need to adapt with a lot of widgets since the window controls are on the right

**Comment by damywise** [comment]
Yeah I tried implementing it and it kinda looks off but I guess it's a tradeoff 

https://github.com/foss42/apidash/assets/25608913/2c671ebd-f60d-457a-a2b2-916fbd6ff295

**Comment by damywise** [comment]
Ah, looks better by enabling the same padding as macos

![image](https://github.com/foss42/apidash/assets/25608913/c97f2467-068d-47d9-b444-8a7d51bcff77)

**Comment by animator** [comment]
Thanks for the feedback @damywise 🙂 I too agree the Windows titlebar does not look well, especially in dark mode.
Looks like you have already done some experimentation. 
Can you send across a PR.

Cheers!
