### ISSUE TITLE
Ability to override content-type for POST request

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#90]
Currently, Content-Type is set as `application/json; charset=utf-8` for POST requests with JSON body. Some legacy APIs only accept `application/json` as content-type in request headers which leads to error. There should be an option to override it.

**Comment by jassirr** [comment]
Hello, @ashitaprasad,
can i take up this issue!

**Comment by ashitaprasad** [comment]
Sure @jassirr waiting for your PR.
If you have any doubt/query feel free to post it in our discord channel [#foss-apidash](https://bit.ly/fgfossd)

**Comment by ashitaprasad** [comment]
The encoding (`charset`) is compulsorily passed by `http` library so the exact use case described is currently not possible. But, still solving this issue helps pass custom content-type for POST requests.
