### ISSUE TITLE
Support for multipart/form-data in request body

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#92]
Currently API Dash only supports text and json request body. 
Support should also be provided for multipart/form-data.

**Comment by vidya-hub** [comment]
Hi @ashitaprasad  

I want to work on this issue,
I already started the basic implementation of this feature,

can I know what exactly the UI/UX for this?

Thanks

**Comment by ashitaprasad** [comment]
Hi @vidya-hub Thanks for taking up the issue. 
We have not yet decided the UI/UX for it so you can share some initial designs here so that we can discuss & finalize it.

**Comment by vidya-hub** [comment]
Sure @ashitaprasad 
Thank you.

**Comment by vidya-hub** [comment]
![Screenshot 2023-12-19 232129](https://github.com/foss42/apidash/assets/59490902/2aa6f71c-cc00-4f4a-b828-dd2e7ea7f346)
![Screenshot 2023-12-19 232142](https://github.com/foss42/apidash/assets/59490902/b897a4be-2a2b-437d-9d69-81c9442c068f)
![Screenshot 2023-12-19 232232](https://github.com/foss42/apidash/assets/59490902/80b3cad2-b56d-4cb6-980a-3b07c87273de)


These are things that i have implemented till now,
I have given drop down option to select content and form-data type.
