### ISSUE TITLE
Add an option to install from FlatHub

### ISSUE THREAD

**Issue by arvl130** [foss42/apidash#93]
**Tell us about the task you want to perform and are unable to do so because the feature is not available.**
I would like to be able to install this app on any Linux distribution.

**Describe the solution/feature you'd like us to add.**
To achieve that, I believe packaging this app as a Flatpak and publishing it on FlatHub would be a good solution. It would also allow the developers to directly deliver updates to Linux users.

From the Flatpak documentation:
>Flatpak is a framework for distributing desktop applications across various Linux distributions.

It is a 'system for building, distributing, and running sandboxed desktop applications on Linux.'

More information on how Flatpak is useful for building desktop apps on Linux can be found on their [Introduction](https://docs.flatpak.org/en/latest/introduction.html) page. You may also check [FlatHub](https://flathub.org/) which is the default repository for Flatpak applications.

**Any other feedback you would like to provide regarding the site.**
I think the site is pretty good. If this feature request ends up being implemented, I believe the Flatpak option should be added to the website. Or preferably, it should point Linux users to the FlatHub webpage as the default channel for app distribution on Linux.

**Comment by animator** [comment]
Closing this issue as we have moved it to our primary discussion thread https://github.com/foss42/apidash/discussions/240
@arvl130 Please subscribe to it to stay in the loop. Thanks!
