### ISSUE TITLE
The folder option is missing in the main branch.

### ISSUE THREAD

**Issue by sagarmahobia** [foss42/apidash#99]
The folder option is missing from the codebase but is available in the last released app for Mac.

**Comment by animator** [comment]
Currently, it is a WIP and will be merged at a later stage when it is stable.

**Comment by Michal-Szczepaniak** [comment]
@animator Would you mind dropping a hint when the later stage is going to happen? I would **REALLY** love to have it, but its all up to you no pressure just bringing some light to it
